### ISSUE TITLE
periodicity of Department of State Dashboard automatic refreshes

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#107]
Determine the periodicity of refreshes based upon UX and load testing.

**Comment by ranweiler** [comment]
Note: right now we refresh 1x/sec.

**Comment by dmzimmerman** [comment]
I think we should refresh far less often. See #290

**Comment by kiniry** [comment]
Like #290, I'm moving this to the next milestone so that we have data.

**Comment by ranweiler** [comment]
This was duplicated by #290, but there's more conversation there, so closing this one.
