### ISSUE TITLE
Audit Board members cannot be of same party

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#163]
So if user notes the same party (both Republican or both Democrat) for the two Audit Board members, there should be an error.

**Comment by nealmcb** [comment]
How about two different minor parties (which are not distinguished in the current UI)?

**Comment by sfsinger19103** [comment]
We're not going to be able to catch that.

Stephanie Singer
Principled Project Lead
Free & Fair <http://freeandfair.us>
267-414-3119

**Comment by nealmcb** [comment]
Should the tool approve one major party member and one unaffiliated? Or a major and a minor? Or a minor and an unaffiliated?

**Comment by kiniry** [comment]
This is in the specification now as a TBD.  See `audit_board_members_political_parties_disjoint`.

**Comment by sfsinger19103** [comment]
All of the cases Neal mentions should be allowed by the tool. In addition the tool should allow,
6. A Democrat and a Republican

In other words, there are only two disallowed cases:
1. Two Republicans
2. Two Democrats.

**Comment by kiniry** [comment]
We need input from CDOS on this prior to doing any development.  

CDOS, should this constraint on audit board membership be enforced by the tools, or by statue and rules?

**Comment by sfsinger19103** [comment]
Follow CDOS mock-up. Enforcement is not done by the RLA Tool.
