### ISSUE TITLE
Add hash upload mechanism

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#179]
Ballot manifests and CVRs must be uploaded concurrent with their SHA-256 hashes.  The County Dashboard UI needs to include appropriate fields, the syntactic legitimacy of input on the client should be checked before the POST is called, and the BallotManifestUpload endpoint needs to have hash support added.

**Comment by ranweiler** [comment]
The server side of this is now done.

**Comment by ranweiler** [comment]
The client HTTP integration part of this was done on the way to #221. We only need to add the visible form.
