### ISSUE TITLE
End of round page

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#181]
What should happen when Audit Board submits the interpretation of the final ballot in the round? Right now the same ballot comes up for interpretation. Instead there should be some kind of end of round page with sign off

**Comment by kiniry** [comment]
In the current specification either the audit is underway or the audit is complete.  Reaching the end of a "round" where the audit is not yet complete means that more ballots should be revealed.

**Comment by sfsinger19103** [comment]
OK, say I'm an Audit Board member in Chaffee County. When the audit began, a list of 5 ballots was assigned to Chaffee County. With my fellow Audit Board member, we have reviewed the first four ballots. The RLA Tool presents us with the interpretation-entry page for the fifth ballot. We complete the interpretation of the fifth ballot and click "Review". Presumably the ballot review screen appears. Does the button at the bottom say "Submit and Next Ballot"? What happens when we click that button?

**Comment by kiniry** [comment]
Given our lack of clarity wrt "rounds", this is a question for CDOS to answer, so I am labeling it as such.

**Comment by ranweiler** [comment]
Blocked on #504.

**Comment by sfsinger19103** [comment]
Yes, there should be an end-of-round page. See CDOS Audit Board Mockup https://drive.google.com/drive/u/1/folders/0B49Sp6YEndrsMTU1Nl8yZDJLZkU

**Comment by ranweiler** [comment]
Opened #514 to capture the UI work now required.
