### ISSUE TITLE
Add pervasive, user-friendly error messages

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#186]
In particular, ensure we give specific, contextualizing feedback based on server error messages.

**Comment by ranweiler** [comment]
As of phase 2, we're now doing this in many important places. We should audit the main user workflows one more time, make new issues for any missing feedback points, then close this out.

**Comment by kiniry** [comment]
@sfsinger19103 and @mkiniry, based upon your testing as non-developers of the tool, what are your impressions of its current feedback?  Is it good enough to call it done for `phase-3`?
