### ISSUE TITLE
clarify event vs. transition terminology

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#195]
Ensure that we are clear about the relationship between these concepts in our specification and our implementation.  Right now it is a bit mixed up in stage-1's implementation.

**Comment by dmzimmerman** [comment]
I don't think the concepts are mixed up in the current phase 1 implementation, really.

**Comment by dmzimmerman** [comment]
I'm closing this issue now, since I don't believe there's any confusion about it anymore.
