### ISSUE TITLE
Make sure Run Book text matches hash upload utility

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#197]
In particular, what can go wrong? How does system respond to errors or hash values not matching?

From Neal: I thought we were hoping to at least tell them the hash doesn't match our calculation so they can try again if they like.
We have to deal somehow with what happens if they re-upload anyway, I assume.
What would help the most is to display the tabulation output, even if it is in a very simple format like a csv of county,contest, candidate, votes, or even just a list of winners per contest."

**Comment by kiniry** [comment]
The UI now provides more detailed feedback on upload failures.  It still needs to be tuned a bit for the final release, and the documentation must reflect all of the possible error states during the workflow. CC @mkiniry

**Comment by kiniry** [comment]
@mkiniry and @sfsinger19103, please update this issue to reflect the final state of the `stage-3` documentation and, if appropriate, close this issue.
