### ISSUE TITLE
annotate `Asm` class and its children for persistence

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#206]
I believe that `Asm` and its children, particularly `RlaToolAsm` are ready for annotation so that they can be persistently stored in the DB.  Doing so will permit us to snapshot the state of the tool with each client action that changes state, permitting us to be completely transactional and reliable even in the face of system or DB failure.

**Comment by dmzimmerman** [comment]
This may be a silly question (that I should have asked before)... but why is this class called `Asm` and not `ASM`? Acronyms are definitely allowed (see, e.g., `CVRContestInfo`).

**Comment by dmzimmerman** [comment]
I think that in order to get this into the database in any kind of reasonable fashion, we'll have to replace the `Map<Pair<AsmState, AsmEvent>, AsmState>` with a `Set<Transition>` (where `Transition` is an entity with the 3 obvious fields).

**Comment by dmzimmerman** [comment]
We're not going to actually do this. Instead, I think we're going to have a separate `PersistentASMState` class that has various information that lets us reconstruct the states of our various ASMs from the DB.
