### ISSUE TITLE
add support for reading the ASM from the DB

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#207]
Blocked on #206.

**Comment by dmzimmerman** [comment]
I'm assuming that the `PersistentASMState` class will take care of this, in conjunction with a query method that I have yet to write. Basically, I imagine there being a single ASM for the DoS dashboard, a single ASM for each county dashboard, and a single ASM for each audit board dashboard, with the latter ones in a map from `County` to the ASM; then, another map from ASMs to PersistentASMState objects that can be refreshed from the database and updated from the ASMs (and, one hopes, therefore committed to the database) in a very straightforward way at the beginning and end of each endpoint computation, respectively.

**Comment by dmzimmerman** [comment]
Completed in #220
