### ISSUE TITLE
fully integrate front-end and back-end

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#209]

**Comment by kiniry** [comment]
Please close this ticket when integration is considered finished for end-to-end testing, @dmzimmerman and @ranweiler!

**Comment by ranweiler** [comment]
When #205 is done and merged, this issue will be closed.

**Comment by kiniry** [comment]
Eventually #209 needs a characterization of which endpoints are still not integrated.  Not a priority right now.

**Comment by kiniry** [comment]
As #205 is merged, I'm closing this issue.
