### ISSUE TITLE
Update server endpoint API 

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#212]
The following is a list of API changes requested for the server endpoints.

- [ ] `UploadRandomSeed`: accept the seed via the HTTP body, not a query param. The body should be a JSON document of schema `{ seed: <string> }`.
- [ ] `AuthenticateStateAdministrator`: accept username/password as JSON, not query params. Use schema: `{ username: <string>, password: <string> }`.
- [ ] `AuthenticateStateAdministrator`: do not expect a `second_factor` value in the initial client authentication request.
- [ ] `RiskLimitForComparisonAudits`: as risk limit as JSON, not a query param. Use schema: `{ riskLimit: <number> }`.

**Comment by dmzimmerman** [comment]
UploadRandomSeed - c892341
Authentication - 7dfc874  (I kept the old way too, for in-browser testing, for now)
Risk Limit - b4eb931

time for sleep
