### ISSUE TITLE
Clarification on inclusion of 'Identifying County Users Page'

### ISSUE THREAD

**Issue by mkiniry** [FreeAndFair/ColoradoRLA#219]
The CDOS ASM goes straight to establishing the risk limit after authentication, whereas the Run Book breakdown has a step between where the CDOS gets to determine, for each individual County, which user will be able to log in to the County-facing part of the RLA Tool?

Joe said in a slack message: It is my understanding that we handle the authentication set up and that is not part of the user interface for them.

**Comment by kiniry** [comment]
They are completely responsible for setting up the authentication server and identifying which credentials are assigned to which dashboards.  The final version of the User Manual and Run Book will highlight this user experience and the current debugging login UI will disappear.  This relates to PR #294.

**Comment by kiniry** [comment]
@sfsinger19103 and @mkiniry, please update this issue as well given the `phase-3` user documentation.

**Comment by sfsinger19103** [comment]
Run books and user manual now match the 2FA user experience.
