### ISSUE TITLE
Convert TabulatorNum, BatchId, and RecordId from CVR: string to integer

### ISSUE THREAD

**Issue by nealmcb** [FreeAndFair/ColoradoRLA#228]
The fields `TabulatorNum`,`BatchId`,`RecordId`,`ImprintedId` in a Dominion 5.2 CVR in csv format are all represented as strings. This interpretation is reinforced by the `ImprintedId` field, shown for example for a CVR with scanner id 3, batch 800 and sequence number 3 as `="3-800-3"` in the sample data provided. Note that the spurious `=` used in these fields is a separate topic being reviewed by Dominion.

See [`test/dominion-2017-CVR_Export_20170310104116.csv`](https://github.com/FreeAndFair/ColoradoRLA/blob/1ba906a8c5c69ff2d23c0b6342259756638ceb83/test/dominion-2017-CVR_Export_20170310104116.csv) for an example.

They are thus stored as strings in the RLA tool database.  

But representing them as strings makes little sense, especially for `RecordId`, which is a numerical sequence number of a ballot in a batch.  This is an issue especially when sorting them into order, both for verifiable random selection and for presenting the randomly selected ballots to the counties for retrieval. Counties probably want to see batch "10" after batch "9", not after batch "1".

The types of these fields are not specified in the _CVR export file format_ documentation from Dominion. But a closer examination of the JSON version of these files shows that these fields are represented as integers there. (Note that `TabulatorNum` is shown as `TabulatorId` in the JSON files, and there is no `ImprintedId` field there.)

Given that these are ints in the more-canonical JSON formats, these fields in the CVR.csv file should probably be converted to int when read in, and the RLA tool should reject any CVR or manifest which has non-numeric data in these fields. Then the records can easily be properly sorted.

Until this change is made, it may be possible to generate CVRs and manifests in which these ids show up with leading zeros, so that sorting by string will produce a natural numeric order.

This proposed resolution is pending review by the Department of State and Dominion.

**Comment by dmzimmerman** [comment]
Making this change has consequences for how the client handles data, and has no real effect on the data stored in the database other than a change in column type, so I don't want to do it without @ranweiler's buy in; however, if he's OK with the change, it should be very straightforward to make it.

**Comment by ranweiler** [comment]
I'm fine with this, but let's defer it until Phase 3.
