### ISSUE TITLE
rollback failures in DB

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#230]
Think carefully about what to do in the situation that a failed transaction cannot be rolled back.  See `AbstractEndpoint.after()`'s final lines.

**Comment by dmzimmerman** [comment]
I still don’t understand under what circumstances this would occur other than database crash. By definition, if we attempt a rollback, either we chose not to commit the transaction (because of ASM violation or the like), or the commit failed. In either case the database should be unharmed.

**Comment by dmzimmerman** [comment]
I'm tempted to close this, but we may want to take another closer look for phase 3.
