### ISSUE TITLE
Fix File Upload Protocol

### ISSUE THREAD

**Issue by dmzimmerman** [FreeAndFair/ColoradoRLA#244]
The current file upload protocol breaks the transactional nature of the server and its state machines, because it requires committing the endpoint's transaction before actually making the state machine transition. This is because files are streamed into the database in `endpoint()` (or a method called by `endpoint()`, but the actual stream objects (and `Blob` helpers) go out of scope before the database commit (in `AbstractEndpoint.after()`) occurs - when this happens, the file streaming fails.

My suggested approach is to do all file uploads in 2 parts: 
1. the actual file upload, which requires authentication but does not affect a state machine - this would return a unique ID for the file, which could be used for...
2. the operation to be done on the file (upload CVRs, upload ballot manifests), which would take that unique ID as part of the request and work with that uploaded file

This would also make file uploading be a smaller transaction, since it currently involves streaming and hashing the file, as well as parsing and record generation in the database. Separating those two aspects should help with performance and responsiveness.

**Comment by dmzimmerman** [comment]
As part of this, each uploaded file in the database would gain an additional status indicator saying whether it had been processed, and would probably only be allowed to be processed once; and any unprocessed files older than a certain age could be cleaned up in some automated fashion at some point.

**Comment by ranweiler** [comment]
:+1: This is just a much better way of doing this. It requires more client requests, but dodges the "hold your breath while we process this big file" problem.

**Comment by nealmcb** [comment]
A bit more of a pain to test also, but seems quite worthwhile.
This is also amenable to future support for an alternate upload practice of having the counties upload the files via their existing infrastructure (e.g. via secure ftp), and then pointing to where it was uploaded.

**Comment by dmzimmerman** [comment]
Half of this is done; the rest of it is easy to do, but will not be done for phase 2 unless @ranweiler wants me to do it for phase 2.

**Comment by ranweiler** [comment]
No, let's save it for phase 3.

**Comment by ranweiler** [comment]
This is done and integrated with the client as of #498.
