### ISSUE TITLE
add support for running the server with no authentication

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#248]

**Comment by dmzimmerman** [comment]
This cannot happen without fundamental changes in the way the system uses the data it gets from authentication; in particular, it uses the county identifier for the authenticated county administrator to do all sorts of things, from picking the right ASM to accessing the right dashboard and labeling uploaded files/database entries/reports. That is why the set of accounts in the `test` directory - including a county administrator for each county, with no password - exists.

**Comment by kiniry** [comment]
Given the system design, I'm going to label this as a `wont-fix` and close it.
