### ISSUE TITLE
integrate ComparisonAudit into server

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#250]
We need to actually run the RLA algorithm in two places:
 - within the DOS Dashboard each time a contest is selected for audit
 - within the Audit Board Dashboard each time a prefix of CVRs/ballot cards under audit have been audited

**Comment by nealmcb** [comment]
We should have an endpoint to run it on request for a given county. And/or just run it and return the data for every refresh of the appropriate type.

**Comment by dmzimmerman** [comment]
What data needs to be returned that isn’t returned by the county dashboard now? And why does it need to be run in the DoS dashboard at all?

**Comment by nealmcb** [comment]
Here is the issue in which I crystallized the concept of a "dashboard" for the RLA, de novo. The use we're making of the term has always seemed odd to me. I think of a dashboard as unified UI to the relevant current state.  I think the SoS and the public (someday) should have an up-to-the-minute overview of all contests in the state, like this: https://github.com/FreeAndFair/OpenRLA/issues/63

**Comment by dmzimmerman** [comment]
To the extent that this needs to be done for phase 1, I believe it is done. We should file a new ticket for enhancements for later phases.

**Comment by dmzimmerman** [comment]
#270
