### ISSUE TITLE
Assess, implement actions for miscellaneous/common endpoints

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#259]
There are some backend endpoints that don't strictly belong to either the DoS or County dashboards. Some may not actually be necessary/desired (this needs to be assessed).

- [ ] `GET /ballot-manifest` (`BallotManifestDownload`)      
- [ ] `GET /acvr/county` (`ACVRDownloadByCounty`)      
- [ ] `GET /cvr` (`CVRDownload`)      
- [x] `GET /cvr/id/:id` (`CVRDownloadByID`)      
- [ ] `GET /ballot-manifest/county` (`BallotManifestDownloadByCounty`)      
- [ ] `GET /cvr/county` (`CVRDownloadByCounty`)      
- [ ] `GET /acvr` (`ACVRDownload`) 
- [x] `GET /contest` (`ContestDownload`)
- [ ] `GET /contest/id/:id` (`ContestDownloadByID`)      
- [x] `GET /contest/county` (`ContestDownloadByCounty`)

**Comment by dmzimmerman** [comment]
You will need some of those to actually get the information for contests and CVRs that is provided by ID in the various lists you get from other endpoints. But yes, some of those are probably not going to be needed later on, and are mainly useful for testing and debugging.

**Comment by ranweiler** [comment]
We currently have a functional, integrated system. Any endpoints on this list that don't yet have an integration, but need one, we will implement incidentally when fixing other issues.
