### ISSUE TITLE
double-check all uses of old ok() method in AbstractEndpoint

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#262]
See:
ACVRUpload
endpoint(Request, Response)
AuditInvestigationReport
endpoint(Request, Response)
AuthenticateCountyAdministrator
endpoint(Request, Response) (2 matches)
AuthenticateStateAdministrator
endpoint(Request, Response) (2 matches)
BallotManifestUpload
parseAndPersistFile(Response, Integer, UploadInformation)
BallotNotFound
endpoint(Request, Response)
CVRExportUpload
parseAndPersistFile(Response, County, UploadInformation)
EstablishAuditBoard
endpoint(Request, Response)
IndicateHandCount
endpoint(Request, Response)
RiskLimitForComparisonAudits
endpoint(Request, Response)
SelectContestsForAudit
endpoint(Request, Response)
UploadRandomSeed
endpoint(Request, Response)
```

**Comment by dmzimmerman** [comment]
Done as of 9ce27fb

**Comment by dmzimmerman** [comment]
#270
