### ISSUE TITLE
Fix AbstractEndpoint logging

### ISSUE THREAD

**Issue by dmzimmerman** [FreeAndFair/ColoradoRLA#265]
Right now, AbstractEndpoint logs whenever one of its various success/failure methods is called. This is problematic because a failure can occur in the ASM after the endpoint proper has called such methods, so you can get both a success and failure logged for the same endpoint. We should hold off on the logging until the `after()` routine.

**Comment by dmzimmerman** [comment]
This is also where we should start logging events to the database in a way that ensures log provenance (i.e., making a hash chain of log entries).

**Comment by kiniry** [comment]
@dmz has implemented the hash chain of log entries in PR #295.

**Comment by nealmcb** [comment]
Thanks - it's vital to have good protection of log provenance. But for that to be useful to the public and auditors of the audit, we need to log in a way that includes full information on all transactions and client requests that affect the audit calculations, and also avoid logging anything that can't be shared with the public. Then independent software can read the log, re-compute the hashes, and verify that the transactions result in the same risk level calculations, audit outcome etc.

Perhaps a straightforward way to do that is to just log the JSON content of all web requests, along with the associated `county_id` when relevant, and presumably the `username` that was authenticated for that request, and the final result of processing it (i.e., success, invalid, and any other possible outcomes). That would be helpful for development also.

Note that if they show up in separate log lines, tying them together with some sort of web request_id would be important. 

Is any of that information considered not releasable to the public? We've working thru the issues of making the CVRs and CVR commitments releasable. Anything else?

**Comment by nealmcb** [comment]
Results of intermediate calculations should also be explicitly logged, like "`In request_id 31415 for CVR 4120, ACVR reports 1-vote overstatement for contest 42`", as well as the tally of each CVR and eventually the final tally and closest margin for each contest (across multiple counties).

**Comment by dmzimmerman** [comment]
This seems to me to be a bit beyond the scope of what the server should be logging, since it can be replicated by actually using the data in the database.

**Comment by dmzimmerman** [comment]
Addressed in PR #392
