### ISSUE TITLE
Fix misspelled county dashboard field name

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#269]
This misspelling is visible in the derived JSON serialization key. See [here](https://github.com/FreeAndFair/ColoradoRLA/blob/master/server/eclipse-project/src/main/java/us/freeandfair/corla/json/CountyDashboardRefreshResponse.java#L108).

**Comment by dmzimmerman** [comment]
Fixed in 165e353

**Comment by dmzimmerman** [comment]
#270
