### ISSUE TITLE
Allow CSV download of round ballots to audit

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#272]

**Comment by kiniry** [comment]
This is the important UI element and client feature discussed in Slack just now.  I had imagined that the full list was simply obtained by pressing a "Download Full List" button adjacent to the audit board page portion highlighted in [this note](https://docs.google.com/a/freeandfair.us/document/d/18ON3DJwn56puC0foO-gRJaXp45PckbM-BWnCVlDg4vg/edit?disco=AAAAA_xrHsE).

**Comment by nealmcb** [comment]
See also #125

**Comment by ranweiler** [comment]
So, we display this list for the current round for each county, in the start of `/county/audit`. Some questions:

1. Do we want a _new_ page that shows _all_ estimated ballots to be audited? If so, which values in the county dashboard refresh response should be used to compute that list (the `start` and `ballot_count` params)?
1. Do we want to be able to download the list for a single round?
1. Do we want to be able to download the list for all currently-estimated ballots to be audited?
1. Do we ever want any of these pages to include ballots that have already been audited?

**Comment by nealmcb** [comment]
The initial cut at this should just display, in the page, the elements listed at #125 for the exact single round the county is in, as far as I have heard and seen in the spec.
There are other issues related to your questions out there and to be generated based on feedback to make it more flexible, allow downloads, allow custom ranges, maybe mark what has been audited already, etc.

**Comment by ranweiler** [comment]
Server side of this is now done in #701, unblocking the client.
