### ISSUE TITLE
County Admin wants to know how many ballots

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#277]
Suppose I'm the county admin for Kit Carson County. My audit board is about to get to work and I want to be ready to pull all the ballots that they are likely to need for the day. Also, audit board member Robin has to pick up a kid at daycare at 3pm and wants to know about how long the audit will take. I hope we'll be done by 2:30, which we can be if we don't have to audit more than 20 ballots. 

I know that if the audit board finds a lot of discrepancies in the wrong direction, we'll have to stay longer and look at more ballots. But I'm an optimistic person! So let's ignore that possibility for the moment. 

How can I find out from the RLA Tool how many ballots we're going to audit (assuming we don't find overstatements along the way)?

**Comment by sfsinger19103** [comment]
Hi, I'm back, still the county admin for Kit Carson County. Geez, what a day, and it's only one o'clock. We found a lot of overstatements already! This is going to take longer than I expected, and Robin will have to call someone to arrange for kid-pick-up and babysitting. But until what time? 

I'm a fervent optimist, and I don't think we'll find any more overstatements in the next batch. 

How can I find out from the RLA Tool how many more ballots we're going to audit (assuming we don't find overstatements along the way)?

**Comment by dmzimmerman** [comment]
This is actually a surprisingly easy thing for us to add. It's basically already there, we're just not displaying it anywhere. So it's the UI/UX parts of this that are critical, because adding support on the server for "optimistic estimate based on current data" is literally a 5 minute task.

**Comment by dmzimmerman** [comment]
(right now, the server is doing "pessimistic estimate based on current data" when it reports the "estimated number of ballots to audit"; we should review that after phase 1 to see what we really want to do there)

**Comment by kiniry** [comment]
Let's get input from CDOS on this feature idea.  I'm labeling appropriately.

**Comment by sfsinger19103** [comment]
CDOS has answered clearly for the beginning of the audit: show the County the minimum number n_1 of ballots such that the audit would end if examining that number of ballots showed no overstatements. The only remaining question is how to calculate n_2, the number of ballots to show the County after the first n_1 ballots have been audited.

**Comment by kiniry** [comment]
We asked CDOS about this today.  They'd like this column of information strictly on the DOS dashboard.

**Comment by sfsinger19103** [comment]
We need a good short title for this column. CDOS wants the "Remaining to Audit" column to reflect what remains in the round. 

Perhaps "Remaining in Round" for the one column, and "Est. Remaining in Audit" for the other?

I hope CDOS will agree to let us put the "Est. Remaining to Audit" info in only one table. I suspect that will be the "County Update" table on the SoS homepage.

**Comment by sfsinger19103** [comment]
Answer to original story:  if Kit Carson County Board member Robin wants to know how much work is left, ask CDOS.

**Comment by sfsinger19103** [comment]
Implementation plan is in issue #546
