### ISSUE TITLE
Fix spurious re-authentication

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#279]

**Comment by kiniry** [comment]
This bug is still present and needs to be fixed for the demo today, @ranweiler.

**Comment by kiniry** [comment]
Or maybe I'm misunderstanding the proposed UI behavior.  If I'm a DOS and I click on a county name, what *should* happen?  If I try to authenticate to the county admin for the county I clicked on I get a blank browser window.  I had expected to see that County's County Dashboard, (or something else), with no authentication.  We should just remove those hyperlinks completely from the UI for the demo today, methinks.

**Comment by ranweiler** [comment]
Temporarily removed links.
