### ISSUE TITLE
Constrain cross-origin requests

### ISSUE THREAD

**Issue by dmzimmerman** [FreeAndFair/ColoradoRLA#281]
Right now, the server allows cross-origin requests. This should be constrained in a later version of the software.

**Comment by ranweiler** [comment]
We will use a reverse-proxy setup to rewrite `/api/...` calls, and let us sidestep any needs for CORS headers configuration.

**Comment by dmzimmerman** [comment]
Moreover, the mechanism for actually setting the CORS headers is now in place (and user configurable).

**Comment by dmzimmerman** [comment]
I believe this to be complete.
