### ISSUE TITLE
Evaluate Dashboard Refresh Intervals

### ISSUE THREAD

**Issue by dmzimmerman** [FreeAndFair/ColoradoRLA#290]
Currently the county dashboard refreshes once per second; I haven’t looked to see how often the state dashboard refreshes. The vast majority of these refreshes are unnecessary, as nearly all actions in the system are synchronous and we don’t expect multiple concurrent users on the same county dashboard as a primary use case. We should figure out a way to minimize them, and also make the server not log them (or ASM state refreshes) or only log them in extreme debug mode.

**Comment by kiniry** [comment]
This no longer seems to be an issue.  I imagine that we might reflect differently on this when 50-odd counties are testing the system simultaneously.  The server logs from those tests will be very illuminating.  As such, I'm moving this to the next milestone.

**Comment by ranweiler** [comment]
We are moving to the following model in #740:
- For any given component, it can either "sync", by firing off a request for data when it is first user-visible (really: mounted to the DOM), or "poll", firing recurring sync requests while mounted. It will then stop polling when unmounted from the DOM.
- Production poll frequency will be once every 30 seconds, debug build is every 5.
