### ISSUE TITLE
Should we keep the "election type" radio form?

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#304]
Right now, the user can choose between "Coordinate Election" and "Primary Election", but we don't do anything with the form data. Should we disable it temporarily, or remove it altogether?

**Comment by ranweiler** [comment]
Per @sfsinger19103, we will keep it in, even though it is effectively a dummy form right now.

**Comment by sfsinger19103** [comment]
CDOS wants to have the info from the election type radio button on the first Audit Board screen. From the mock-up:

[Screen 1]
[County Name] County [Election Date] [Election Type] Election
Audit Board Reporting Utility for Risk-limiting Audit
[State] [County] Ballot Contest
Click here to proceed

https://docs.google.com/document/d/18ON3DJwn56puC0foO-gRJaXp45PckbM-BWnCVlDg4vg/edit

**Comment by dmzimmerman** [comment]
OK. AtteFrom the server side, this will be a new endpoint `/set-election-info`, that simply sets those strings in the DoS dashboard. Request body should look like:

```
{ "election_type": string,
  "election_date": string that is hopefully parseable as a date }
```

Is there any other such information we have to save that I'm missing?

**Comment by ranweiler** [comment]
@sfsinger19103 @dmzimmerman can we open new issues that track the specific action items for this work? This issue was just for figuring out if we wanted to keep the forms.

**Comment by ranweiler** [comment]
I'll create them.

**Comment by dmzimmerman** [comment]
Go right ahead.

**Comment by ranweiler** [comment]
Added #537 and #538.
