### ISSUE TITLE
Should the election date form be editable?

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#305]
It should also be persisted.

**Comment by sfsinger19103** [comment]
There should be no restrictions on the Secretary of State's ability to edit the "election date" value at any time. In other words, if the Secretary of State were to enter the wrong date for the election at any time, the Secretary of State should be able to change it easily.

Does that answer your actual question?

**Comment by ranweiler** [comment]
Yes, this answers this question. Thanks @sfsinger19103!
