### ISSUE TITLE
Include uploaded manifest/CVR export file names in county dashboard response

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#311]
This way we can render it in the UI between refreshes, along with the hash.

**Comment by dmzimmerman** [comment]
I haven’t been saving file names, mainly because I never see file names. When a file is uploaded I save a timestamp and the county that uploaded it along with its hash status and the actual data. Since the same county is extraordinarily unlikely to upload two files in the same nanosecond, this is sufficient identifying info. When uploads are re-implemented in a few days we will also be saving a unique ID. For now, I could send the file timestamp in the county dashboard refresh I suppose, then you’d have full identifying info.

**Comment by ranweiler** [comment]
@dmzimmerman the client _does_ include the filename as part of its file upload request (just verified that it is part of the form data serialization). If you can figure out how to extract it from the form data, and save it, that is what will allow us to persist the filename in the UI between refreshes/logouts. 

It isn't critical right now, but would be a good usability enhancement (at a minimum, it would be _surprising_ if the system doesn't appear to know the name of the file a user uploaded; many of our users probably won't instinctively think "hash == my file").

**Comment by dmzimmerman** [comment]
If you tell me where it is on the form, I can probably grab it and save it (with a minor database schema change - but the database schema for uploaded files is going to change dramatically anyway soon once the upload method changes as per #244.

**Comment by ranweiler** [comment]
I'm not sure how Spark is parsing the multipart form data, but is serialized as part of the browser-side `File` object. For example, Chrome DevTools shows the file upload request payload as:
```------WebKitFormBoundaryqmEBz8SHUDbMw0RS
Content-Disposition: form-data; name="county"

1
------WebKitFormBoundaryqmEBz8SHUDbMw0RS
Content-Disposition: form-data; name="bmi_file"; filename="arapahoe-manifest.csv"
Content-Type: text/csv


------WebKitFormBoundaryqmEBz8SHUDbMw0RS
Content-Disposition: form-data; name="hash"

42d409d3394243046cf92e3ce569b7078cba0815d626602d15d0da3e5e844a94
------WebKitFormBoundaryqmEBz8SHUDbMw0RS--```

So it isn't a separate form field, but I'm not sure how it is accessible on the Spark side.

**Comment by dmzimmerman** [comment]
Yeah, I don't know either... I can look into it. You could, I suppose, possibly send it as a separate form field as well. I don't think this will happen for phase 1.

**Comment by dmzimmerman** [comment]
I found out how to get the filename; I'll implement it as soon as I reimplement uploading, which may be tomorrow (because it's pretty critical to achieving transactional behavior with the server, and should be done for phase 2).
