### ISSUE TITLE
Ensure uploaded file data from server is rendered in county dashboard

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#312]
If we have a ballot manifest or CVR export hash from the server, we must render it in the county dashboard, and when appropriate, disable those forms.

**Comment by ranweiler** [comment]
This fundamentally works: we disable the forms when we have made a successful upload, and instead show the uploaded data.

Here's what we lack:
1. Form persistence between logouts/refreshes
2. We don't permit a county to re-upload after a successful upload. We _do_ allow multiple unsuccessful attempts.

We don't need 1 in general, nor do we offer it anywhere else. We only need if it we need 2. If we allow file re-uploading _after_ a successful upload, then we can't use the existence of a hash for a successful upload to decide if we should render an editable upload form. Instead, we must use some other state, such has ASM state. If we don't allow file re-uploading at any point after a successful upload, we don't need 1. If we want to allow re-upload, we want 1 _for the permissible re-upload period only_. We will also want the name of the successfully uploaded file, for usability. See #311.

**Comment by kiniry** [comment]
It is my impression that they are going to want to permit Counties to re-upload fixed CVR data with a new hash, and we will have to keep the old upload as a part of the audit log of the election, but use the new data in the audit.  This would be only permitted prior to the random selection happing and the audit starting, of course.  Let's see what CDOS says about this scenario.

**Comment by dmzimmerman** [comment]
This scenario is exactly why CVR records and ballot manifests (and the dashboards that know about them) have timestamps.

**Comment by ranweiler** [comment]
This is blocked on #311.

**Comment by kiniry** [comment]
This is no longer blocked since #311 is closed.
