### ISSUE TITLE
Election Date form should not default to today

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#323]
Easiest fix: have it default to first Tuesday in November of current year

Wanna get fancy? 

Have it default to whichever is nearest in the future:
* the first Tuesday after the first Monday in November (earliest is Nov 2 and latest is Nov 8), or
* the last Tuesday of June in a an even-numbered year. ([C.R.S. 4-101-1]{http://codes.findlaw.com/co/title-1-elections/co-rev-st-sect-1-4-101.html})

See also https://www.sos.state.co.us/pubs/elections/FAQs/GeneralInfoFAQ.html

**Comment by kiniry** [comment]
I'm moving this to the next, polishing, milestone.

**Comment by ranweiler** [comment]
I'm going to make this a client configuration value.

**Comment by sfsinger19103** [comment]
2.     The election and public meeting default dates are hard coded for the 2017 Coordinated election. It would make more sense for the dates to default to the current date so that the user does not have to navigate from a November 2017 calendar to a June 2018 or November 2018 calendar next year.

(from RLA Tool Feedback #1_tool version3.docx)

Need to ask CDOS: this is easy to change for a developer each year, and we can document explicitly how to adjust this. are you sure you want us to default to "today"?

**Comment by sfsinger19103** [comment]
Have decided, rather than asking, simply to implement the CDOS request of defaulting to "today". So this issue is superceded by #800.
