### ISSUE TITLE
Risk Limit Columns on DoS Dashboard

### ISSUE THREAD

**Issue by dmzimmerman** [FreeAndFair/ColoradoRLA#325]
For the list of contests under audit on the DoS dashboard, it seems more useful to display the estimated number of ballots remaining to audit than to display the current achieved risk limit. This can be obtained from the county dashboard data for the county in which the contest occurs (since we don't have any multi-county contests at the moment).

Also, the target risk limit column seems somewhat redundant at present given that we don't have the ability to set risk limits per contest, but in any event, it should be populated right now from the risk limit set on the DoS dashboard.

**Comment by ranweiler** [comment]
Blocked on #409.

**Comment by kiniry** [comment]
This relates to #405 also.  I'm nearly done with the proposed changes to all UIs.

**Comment by ranweiler** [comment]
Closed in #454.
