### ISSUE TITLE
Seed Selection and Contest Selection are out of order

### ISSUE THREAD

**Issue by dmzimmerman** [FreeAndFair/ColoradoRLA#339]
In the state machine diagram (and the state machine implementation), the DoS dashboard should first set the risk limits, then identify the contests to audit, then have the public seed event/enter the random seed, and then publish ballots to audit. In the current implementation, the identification of contests to audit occurs after the random seed entry.

**Comment by dmzimmerman** [comment]
(note that I've initially assigned this to phase 1, but if it's not a super simple thing, push it to phase 2)

**Comment by ranweiler** [comment]
Closed in #205.
