### ISSUE TITLE
design and implement an automated end-to-end smoketest of an entire audit

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#348]
A smoketest should exercise the main end-to-end scenario of an RLA.

**Comment by kiniry** [comment]
@nealmcb has been working on this for some time.

**Comment by kiniry** [comment]
I'll let @nealmcb update this ticket to document any top-level missing features or bugs of the smoketest, much like @ranweiler has been doing on his multi-stage client development in PR #205.

**Comment by nealmcb** [comment]
We have been doing simple end-to-end audits via the Python smoketest main.py client for weeks now. As documented in the git commit log, the testing code continues to get more capable, including now:

* Flexible command-line control over individual phases of the audit
*  setting up a set of county audits with a variety of CVRs and manifests, which can then be performed using the web client interface
*  running multiple audits in separate counties simultaneously
* allowing flexible testing of new endpoints, etc.

The testing client will continue to evolve as driven by feature development and other requests.

**Comment by nealmcb** [comment]
As noted above, basic smoketesting has been implemented and will continue to track the server capabilities, so I'm closing this issue.

The same test client will be enhanced to better support load and performance testing, for issues #350 and  #351.
