### ISSUE TITLE
performance analysis and server bug replication post-CDOS call on Friday 18 August

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#360]
As I do performance analysis of the server with @dmzimmerman on what CDOS witnessed during their first day of testing, I'll update this ticket with what I discover.  I'm also trying to replicate the race condition bug that CDOS triggered this morning.

**Comment by kiniry** [comment]
Running nine concurrent Dept. of State Dashboards results in a server load of between 18 and 66% of one CPU.  This is due to the current default refresh rate of that dashboard of 1 refresh per second, and the fact that the refresh currently triggers a dynamic computation of everything on that dashboard for all contests (i.e., every row of both tables on that dashboard has to be re-computed, per refresh, per client).  @dmzimmerman will open an issue on caching those computations in the DB across sessions and refreshes momentarily.

**Comment by kiniry** [comment]
Uploading a manifest/CVR pair in a county dashboard worked correctly and triggered an update on all DoS dashboard basically simultaneously.

**Comment by kiniry** [comment]
Setting the risk limit in one DoS dashboard and attempting to set/look at the risk limit in all other dashboards works properly.  The first transaction succeeds, the others see that it is already set and is read-only.

**Comment by kiniry** [comment]
After setting the risk limit the Contests Update panel on the DoS Dashboard Home still contains no data.

**Comment by kiniry** [comment]
Selecting contests to audit in one SoS Dashboard is visible across all other SoS Dashboard logins.

**Comment by kiniry** [comment]
Setting the random seed results in the correct Audit Definition Review screen with the right risk limit and seed.

**Comment by kiniry** [comment]
Starting the audit in the County Dashboard that has uploaded the Manifest/CVR file pair results in the Audit Board Sign-in Screen.  Signing in results in no next page though, as the SoS has not started the audit.  I have filed #361 on this bug.

**Comment by kiniry** [comment]
After the SoS launches the audit the Contest Updates pane still contains no data.  The estimated number of ballot cards to audit for the county that has uploaded data is correct and consistent across all nine SoS Dashboards.  The Java VM is now consuming just over 100% of a CPU and Postgres now has a dozen instances consuming, in total, about one CPU.

**Comment by kiniry** [comment]
The county dashboard states that there are 164 ballots to audit (in the **County info** panel).  The SoS Dashboard concurrently states that the county in question has to audit **93** ballots.  It is my understanding that these two numbers should always agree.

**Comment by kiniry** [comment]
When entering the first Ballot verification page, I'm told I need to audit a particular Ballot ID, Ballot Style, and Imprinted ID.  We have filed issue #359 on updating that information.  The UI claims that I am going to have to audit 164 ballots, much like the county dashboard showed me earlier.  Thus, the Audit Board Dashboard agrees with the County Dashboard, but not with the State Dashboard.  

The CVR file contains 164 ballots, so I believe that the County Dashboard is properly summarizing how many ballots there are in the full set of CVRs, but not (as I, and probably an auditor) would presume, the number of ballots that I'm going to have to look at.

**Comment by kiniry** [comment]
The first ballot chosen in my test does not contain the contests under audit.  Performing verification on it and submitting the audit CVR results in the correct review screen.  Pressing "Submit & Next Ballot" results in moving back to the Audit Verification page for the same CVR, complete with all of the buttons I had selected previously still selected, exactly as CDOS had witnessed.

**Comment by kiniry** [comment]
Examining the server log shows that the aCVR was successfully uploaded.  Attempting to move back to the County Dashboard home then starting to audit again results in obtaining the same ballot we just verified.  Pressing "Ballot Card Not Found" results in no UI update and no log on the server of the UI hitting the `/upload-audit-cvr` endpoint.

**Comment by nealmcb** [comment]
Rough smoketest timing, for just main.py, on Neal's machine, of the Phase 1 delivery (commit c4e64b01, "master" here).  Between 3 and 4 times faster for this test, and I hear it is a much better speedup for repeated client refreshes.

The full set of 83 contests, with just one selected (41 to audit, 49 acvrs) took about 2:07 for the current master and just 0:46 for the new code.

With 2 selected, there are 92 to audit, which takes 134 acvrs with the 2-card ballots.

|version|49 acvrs|134 acvrs|
|----|---|--|
|master (c4e64b01)|127|546|
|phase-1-fixes(5f181740)|46|114|

**Comment by kiniry** [comment]
After the work of this weekend, primarily @dmzimmerman's progress on #370, we now see that both the Java VM and the Postgres instances are running under 10% CPU.  Basically, they are bored again.

I also have been unable to replicate the multi-dashboard instantiation bug CDOS reported after Dan's work, so I'm now closing this ticket.
