### ISSUE TITLE
uploading multiple manifest/CVR files successfully

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#365]
@dmzimmerman reports that right now the table containing the CVRs is simply appended and a timestamp determines which set of rows are the most recent CVRs under audit.  As we save the CVR file itself into the DB, rows corresponding to earlier uploads should be deleted from the table.  

Furthermore, if an upload replaces existing data, the server should let the client know this fact and the UI should inform the county administrator that they just replaced old data with new, but the old data was retained for auditing purposes.

**Comment by dmzimmerman** [comment]
This will not be done for phase 2. Right now, the ASM (and the user interface) enforces that files are only uploaded once.

**Comment by ranweiler** [comment]
I would suggest saving this for phase 3, and focusing on a solid-as-possible UX for phase 2.

**Comment by dmzimmerman** [comment]
Sounds good to me.
