### ISSUE TITLE
input on risk limit should be a percentage, not a floating point

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#374]
On the *Administer and Audit* page, the input for *Risk Limits* must be a percentage, not a floating point.  I.e., users expect to be able to input 5%, not 0.05.  Reasonable numeric precision must be supported (say, three decimal places).  

Input of a vanishingly small value should result in a warning message.  I.e., "You input a risk limit at 0.01%, which means a risk limit of 0.0001, which means you want to be 99.9999% sure that the outcome of contests is correct.  Risk limits typically range from 1% to 10%.  Double-check that your are sure you want a risk limit this tight."  This kind of feedback can be in a modal popup.

**Comment by ranweiler** [comment]
This is done in #490, except for the dynamic guidance messaging. I created a new issue for that specifically in #492.
