### ISSUE TITLE
semantics for "No consensus" button on Ballot verification page

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#381]
Should pushing “No consensus” both deactivate all tick-boxes and ghost them?  It is only doing the latter right now.

**Comment by nealmcb** [comment]
The semantics should be clear, but we also want to gather as much clarity and consensus as we can. In a contest with multiple winners, the audit board might be clear on some of the marked choices, but not others. So having a way for the audit board to communicate some marks which it finds consensus around, some non-marks with consensus, and some choices for which the presence of a mark is debatable, might be helpful. That still won't cover all the corner cases, but it would provide useful QA data for election administrators and the public.

**Comment by ranweiler** [comment]
Blocked on response from CDOS.

**Comment by sfsinger19103** [comment]
As of 8/28 email from Dwight Shellman, CDOS has specified: When an Audit Board ticks the “No Consensus” box for a contest, all other tickboxes for that contest will be deactivated and ghosted. Any previously-clicked buttons for that contest will be unclicked.

**Comment by kiniry** [comment]
I'm moving this polish to the next milestone.

**Comment by ranweiler** [comment]
Closed in #602.
