### ISSUE TITLE
Fix effect of ballot-not-found (PHANTOM_BALLOT) on sample size

### ISSUE THREAD

**Issue by nealmcb** [FreeAndFair/ColoradoRLA#396]
As noted in #326, in testing `/ballot-not-found` with smoketest, it returns a 200 response code, but `estimated_ballots_to_audit` doesn't increase. It decreases instead.

**Comment by dmzimmerman** [comment]
Probably addressed by #411, but you'll want to check it when #411 is merged.

**Comment by dmzimmerman** [comment]
@nealmcb, please verify that this has been fixed.

**Comment by kiniry** [comment]
@nealmcb, please verify that this has been fixed.

**Comment by kiniry** [comment]
I'm moving this to the next milestone, given it is in the weeds of the new RLA-with-rounds algorithm and is likely to see tuning given CDOS and EO experimentation with the 1.0 beta tool.

**Comment by nealmcb** [comment]
Yes, I have verified that this has been fixed. Thank you!
