### ISSUE TITLE
File upload should occur before audit board sign-in

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#402]
Right now, both the ASM [diagram](https://github.com/FreeAndFair/ColoradoRLA/blob/master/specs/ASMs/County_Dashboard_ASM.pdf) and [server implementation](https://github.com/FreeAndFair/ColoradoRLA/blob/master/server/eclipse-project/src/main/java/us/freeandfair/corla/asm/ASMTransitionFunction.java#L109) require the audit board to be established prior to uploading the ballot manifest and CVR export files. Instead, the file uploads should be permitted prior to audit board sign-in.

**Comment by dmzimmerman** [comment]
I'm assuming this is now considered fixed?

**Comment by ranweiler** [comment]
Yes, as of #414.
