### ISSUE TITLE
Notify user when uploaded file is malformed

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#419]
If the user tries to upload a ballot manifest or CVR export that cannot be parsed, notify them of this specifically, instead of a generic file upload failure message.

**Comment by kiniry** [comment]
Make sure that, as part of the feedback to the user, we give some useful guidance about what might be wrong.  I realize at the moment our parser might not provide such feedback, but in the future it might.  For now say something like, "We are unable to process your <manifest|cast vote record> file.  Are you sure it is in the right format?  It should be a comma-separated value (CSV) file.  Load it into Microsoft Excel to double-check it contains the data that you think it should. Also, make sure that no one has edited the file by hand after exporting it from your Election Management System."

**Comment by ranweiler** [comment]
Regressed, investigate.

**Comment by ranweiler** [comment]
Closed in #498.
