### ISSUE TITLE
Use Ballot Manifests

### ISSUE THREAD

**Issue by dmzimmerman** [FreeAndFair/ColoradoRLA#424]
Right now, we don’t do consistency checking on ballot manifests or use them to tell counties where to pull ballots from. We should do both.

**Comment by ranweiler** [comment]
I've opened #515 to track the client part of this.

**Comment by dmzimmerman** [comment]
Currently we use them to tell counties where to pull ballots from, so I'm closing this ticket, since consistency checking is outside our scope.
