### ISSUE TITLE
Modify list of reasons for choosing a contest to drive the RLA

### ISSUE THREAD

**Issue by nealmcb** [FreeAndFair/ColoradoRLA#432]
In Colorado's 2017 audits, all contests will be subject to audit, and they will all be interpreted by the Audit Board and entered into the RLA tool.

A subset of contests will be required to attain a risk limit, and these are said to "drive" the sample size and how discrepancies affect when the audit is complete.

In the current user interface, during the selection of the contests that "drive" the audit, there are a set of reasons that can be given for each choice. They derive from the associated text of Rule 25.2.2 (I).

* STATE_WIDE_CONTEST,
* COUNTY_WIDE_CONTEST,
* CLOSE_CONTEST,
* GEOGRAPHICAL_SCOPE,
* CONCERN_REGARDING_ACCURACY,
* OPPORTUNISTIC_BENEFITS,
* COUNTY_CLERK_ABILITY;

Choosing either STATE_WIDE_CONTEST or COUNTY_WIDE_CONTEST makes sense because at least one of each of these is required.
But it is unclear what the benefit is of listing other reasons for any given contest. Several may apply to any given contest, but only one is allowed. In particular, the "OPPORTUNISTIC_BENEFITS" reason doesn't seem to apply, since an opportunistic audit takes place for non-chosen contests rather than chosen ones, and the one about ABILITY actually relates to deadlines and workload, and is more of a reason for not choosing a contest.

So I think the list should be narrowed to only include the first two reasons. Alternatively it could be modified to allow multiple reasons, from a modified set of possibilities.

**Comment by ranweiler** [comment]
@sfsinger19103, @kiniry, do we have consensus on what to do here? Have we received any feedback from CDOS on this issue? Narrowing the set of reasons will be an very simple change.

**Comment by sfsinger19103** [comment]
CDOS hasn't asked us to change the list, so this is low priority.

**Comment by sfsinger19103** [comment]
Per 8/29 afternoon conversation with CDOS, until we hear otherwise the list should have only two entries:

State Contest
County Contest

Note that they specifically do *not* want "statewide" but "state", and not "countywide" but "county.

**Comment by ranweiler** [comment]
Done in #559.
