### ISSUE TITLE
UI revisions for phase-2 and phase-3 deliverables

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#434]
The UI revisions currently suggested for the phase-2 and phase-3 deliverables, as discussed in our meeting today @dmzimmerman @nealmcb and @ranweiler, are located in the `new-UIs` branch.  

In particular, look at the directory https://github.com/FreeAndFair/ColoradoRLA/tree/new-UIs/docs/screenshots/phase-2%20UI%20review for the marked up UIs we discussed.

**Comment by kiniry** [comment]
When you feel that all of the specs covered in `new-UIs` is done @ranweiler, please close this ticket and delete the branch.

**Comment by ranweiler** [comment]
This has been closed out as of the last deliverable (Phase 2 Amendment 2).
