### ISSUE TITLE
attempt to audit an election that is a tie

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#448]
What should we do if the CDOS attempts to audit an election that is a tie according to the CVRs?

CC @dmzimmerman @ranweiler

**Comment by kiniry** [comment]
See `CountyContestResult.contestDilutedMargin`.

**Comment by dmzimmerman** [comment]
Also `countyDilutedMargin`.

**Comment by nealmcb** [comment]
Technically speaking, the end result should be to come up with a very large number to audit, i.e. all the ballot cards in the contest (at least if we were doing selection without replacement).
From a UI standpoint, we would want to guide them quickly to doing a full hand count for that contest. Note that in Colorado, the contest would be up for mandatory recount (after audit and canvass are both completed and certified), so whether to audit it or not is a call for CDOS.
And I wouldn't expect CDOS to choose a tie contest to drive the RLA, such that the calculations would make much of a difference.

**Comment by kiniry** [comment]
We asked CDOS this question today.  They'll get back to us.

**Comment by sfsinger19103** [comment]
Per 8/29 email from Dwight Shellman:

> We understand Dr. Stark’s algorithm depends on reported winning and losing candidates and choices, and does not address tied contests.  We do not believe the RLA Tool needs to address this remote possibility at this time, for several reasons.  


So no need to support audits of tied contests in the RLA Tool.
