### ISSUE TITLE
[Discussion] precise choice of open source license

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#452]
Per discussions in the LICENSE.md file in the repository:

There are ongoing discussions with the Colorado Department of State about which Open Source license is most appropriate for this system.

They have agreed to license it under a variant of the GPLv3, but the final decision about which variant it will be licensed under is still under discussion.

In particular, should it be licensed under [AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html) or [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html)? Please see the FSF document, ["Why the Affero GPL"](https://www.gnu.org/licenses/why-affero-gpl.en.html), for a relevant discussion.

Please use this issue to give feedback on this matter.

**Comment by kiniry** [comment]
Should CORLA be licensed under AGPLv3 with a classpath exception?  http://openjdk.java.net/legal/gplv2+ce.html

**Comment by cjerdonek** [comment]
Is that OSI-approved? I don't see it in their list: https://opensource.org/licenses/alphabetical

**Comment by dmzimmerman** [comment]
GNU Affero General Public License, Version 3. It appears under G, not A.

**Comment by cjerdonek** [comment]
I meant the modified form of AGPLv3 (with classpath exception).

**Comment by kiniry** [comment]
It is our understanding that the "classpath exception" is a specific instantiation of the standard [GPL linking over controlled interface mechanism](https://www.gnu.org/licenses/gpl-faq.en.html#LinkingOverControlledInterface), thus it would not be listed as a separate license at OSI.

**Comment by cjerdonek** [comment]
Okay, thanks!

**Comment by sfsinger19103** [comment]
CDOS said OK to GPLv3, so I'm removing the `Ask CDOS` label

**Comment by catrope** [comment]
If the license has in fact been decided (which the closure of this issue strongly suggests it has been), could LICENSE.md be updated? I'd submit a PR for this, but it's not completely clear to me from the discussion here what the decision was exactly.

**Comment by sfsinger19103** [comment]
Thanks for the ping, @catrope , update of LICENSE.md file is in process. The license chosen is AGPLv3 with a classpath exception.
