### ISSUE TITLE
Confusing authentication behavior even when using incognito or private browser windows

### ISSUE THREAD

**Issue by nealmcb** [FreeAndFair/ColoradoRLA#458]
A variety of issues, such as failures of client actions and authentication failures visible in the server log, can be a result of being logged in multiple times in the same browser context, and having the client use the wrong authentication cookies to send its actions.

Background.

While testing, people typically want to be logged in under multiple roles, e.g. as both a state admin and a county admin, and possibly as  multiple counties.

One simple way to do that is to login with one session, say the state session, in the users normal browser profile, and then use an "incognito window" (Google Chrome terminology), or a "Private Window" (Firefox terminology) to log in as a county session. Cookies are not shared between the user's normal windows and an incognito/private window. Each has its own context for cookies.

Users may assume that opening a second incognito/private window would offer yet another secluded context for another county user or whatever, but it seems that both Chrome and Firefox share cookies across their incognito/private windows, so that is not an option.

Opening 2 more additional sessions in an alternate browser is one approach to taking on additional roles.

Another approach with no limit on the number of simultaneous logged-in roles is to set up a separate Chrome profile for each, as described at [Share Chrome with others or add a profile - Computer - Google Chrome Help](https://support.google.com/chrome/answer/2364824?co=GENIE.Platform%3DDesktop&hl=en)

Firefox also has a [Profile Manager to create and remove Firefox profiles \| Firefox Help](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles), but it requires closing the browser.

This and other error conditions can often be tracked down by opening a JavaScript console window in the browser, e.g. via `Ctrl+Shift+J` (or `Cmd+Shift+J on a Mac).` in Chrome or Firefox.

**Comment by kiniry** [comment]
We need either:
 1. strong documentation about this matter so that users don't do the wrong thing with regards to inappropriate browser use (*I'm not a fan*), or
 2. client-side detection when a user violates this constraint or the server invalidates their credentials (*ask yourself what other polished web app silently behaves in inappropriate ways and leaves the user in the dark*)

**Comment by nealmcb** [comment]
@ranweiler What is the current expected behavior, given #532?

**Comment by ranweiler** [comment]
@nealmcb, if a new user logs in to the _same browser context_ (e.g. w/shared cookies), any pre-existing user will be automatically logged out. Previously, they would _not_ be logged out, but their session ID/cookie would change, which could cause all sorts of problems. If the new user logs into a new browser context (e.g. a different Chrome profile), it will not affect any pre-existing users.
