### ISSUE TITLE
initial number of estimated number of ballots to audit on SOS page incorrect

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#463]
Prior to the SOS starting the audit, the estimated number of ballots to audit on the SOS Main page is `-2147483648`.  It should probably just read `N/A`.

**Comment by kiniry** [comment]
Here is a screenshot.
![image](https://user-images.githubusercontent.com/478911/29700994-c2167932-891d-11e7-9c49-d6b7df32c41f.png)

**Comment by ranweiler** [comment]
@dmzimmerman has identified the source of this problem on the server side, where it is being addressed.

**Comment by dmzimmerman** [comment]
This was, in fact, addressed as part of #468
