### ISSUE TITLE
permitted to start an audit without an audit board

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#471]
If the SOS has started the audit, I am permitted to start the audit in the County Dashboard even though I have not yet signed in an Audit Board.

**Comment by dmzimmerman** [comment]
On the server side this is a duplicate of #467

**Comment by ranweiler** [comment]
I can no longer repro this client side as of #468. I captured the specific need for more user feedback in this cases in #494.
