### ISSUE TITLE
design and implement audit board report export feature

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#474]
We have to implement two kinds of reports for the County: the Audit Board Report and the County Report. The Audit Board Report comes in two flavors, and Intermediate form that is recorded when the Audit Board takes a break or changes, and the Final form when the audit is complete. The County Report can only be filed after the Audit Board report has been filed.

CDOS has requested that the Audit Board Report contain the following information:

*General Requirements*
- Date and Time stamp for each export
- Exports available in PDF and Excel formats

*Audit Board Report*
- Audited contest(s)
- Choice and vote totals for winner
- Choice and vote totals for loser
- Margin between winner and loser in votes
- Number of ballots cast
- Diluted margin in percentage
- Number of ballots that were audited, by round

**Comment by nealmcb** [comment]
Note that there may be multiple winners and losers, and standard RLA theory handles all the possible ways that the outcome may be wrong. The margins reported should at a minimum include the smallest margin, that between the winner with the fewest votes and the loser with the most votes.

**Comment by dmzimmerman** [comment]
It was not clear to me at all from their documentation that this report is separate from the other county report that they asked for (referenced in #473). I had assumed they were one report.

**Comment by kiniry** [comment]
They are one report; this is just a "sub-report" from such.  I imagine in the future we might like to export it separate from the overall county report, thus the separate issue.  Will be closed by #567.
