### ISSUE TITLE
Audit  conclusion

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#480]
Per CDOS 8/25 email:

The County Updates field will be automatically populated after the first ballot in a county’s Ballot verification page has been submitted; the tool proposed that 4 ballots be audited; the State page updates instantaneously after each ballot is submitted but doesn’t provide feedback on when the audit can conclude;

**Comment by kiniry** [comment]
@ranweiler [This part of their UI sketch](https://docs.google.com/a/freeandfair.us/document/d/18ON3DJwn56puC0foO-gRJaXp45PckbM-BWnCVlDg4vg/edit?disco=AAAAA_vOAKA) is what CDOS is referring to in this feedback, I believe.  (Link is only visible to F&F employees.)

**Comment by sfsinger19103** [comment]
Currently County end-of-audit page has this text: 

> All audit rounds are complete. Please use the form below to certify that the county has completed the audit,
with a "Submit" button.

If the form is null (and I suspect it will be) more appropriate would be:

> Congratulations, Acme County, you have completed the audit! 
with a "Download Report" button.

**Comment by sfsinger19103** [comment]
Current page:

![county_end_of_audit](https://user-images.githubusercontent.com/14353822/29955437-7746ad9c-8e94-11e7-8e23-af97cbdf7499.png)

**Comment by ranweiler** [comment]
@sfsinger19103, since (per CDOS) we are scrapping the idea of submitting another report here, should we redirect to the home page, or render your second suggestion above?

**Comment by sfsinger19103** [comment]
Assuming the Home Page has the button for report export, redirect to the home page.

It will be nice if the button text reflects the state (intermediate report vs. final report).

**Comment by ranweiler** [comment]
@sfsinger19103 captured the desired button state dependence to issue #687.

**Comment by ranweiler** [comment]
It looks like we actually implemented the desired behavior back in #594, it just wasn't clear at that time that it was indeed what we ultimately wanted. Closing.
