### ISSUE TITLE
Audit board sign in should enforce name entry

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#483]
Per CDOS 8/25 email:

Selected Democratic party and Republican party with no names associated with the party then selected “Submit & Next”. The tool didn’t require names to be associated with each party affiliation selection.

**Comment by ranweiler** [comment]
This is definitely fixed as of phase 2. There is one further validation we can and should add for phase 3, namely, that entering nonempty blank spaces results in an invalid form state for the audit board sign-in.

**Comment by ranweiler** [comment]
Added #487 to address the above edge case.
