### ISSUE TITLE
Terms & acronyms used should all be defined in User Manual;

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#485]
Per CDOS email 8/25:

the system documentation that accompanied version 0.9.0 is deficient.  Terms and acronyms utilized in the tool are not defined in the user manual,

**Comment by kiniry** [comment]
Please double-check that domain-specific parts of speech used in the user documentation are included in the glossary, per #331, @mkiniry.

**Comment by sfsinger19103** [comment]
CDOS has provided no specific examples, and issue is live in #331.
