### ISSUE TITLE
Run Book deficient

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#486]
Per CDOS 8/25 email:

the system documentation that accompanied version 0.9.0 is deficient.   the run book did not provide the proper order of steps necessary to load, launch and use the tool.

**Comment by kiniry** [comment]
I spoke with @mkiniry about this on Saturday the 26th.  Our expectations for how the user documentation will be polished at the end have always included:

- finishing the glossary (per issue #11)
- documenting exceptional scenarios that users can witness in the tool will be explained, including a screenshot of the UI as well as suggested remediation steps. E.g., if a hash code does not match for an uploaded file, what should the user do? and
- the documents raw contents, which is what you witness during system development, will be professionally polished for style, typeface, layout, etc.

**Comment by sfsinger19103** [comment]
Of @kiniry's three points above, the last two have been addressed, and the first is in #331. CDOS has provided no further feedback on the user documentation, so I'm closing this issue.
