### ISSUE TITLE
Add guiding feedback when user enter unusual risk limits

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#492]
From #374:

> Input of a vanishingly small value should result in a warning message. I.e., "You input a risk limit at 0.01%, which means a risk limit of 0.0001, which means you want to be 99.9999% sure that the outcome of contests is correct. Risk limits typically range from 1% to 10%. Double-check that your are sure you want a risk limit this tight." This kind of feedback can be in a modal popup.

**Comment by ranweiler** [comment]
Related to: #186.

**Comment by kiniry** [comment]
Given that the UI now focuses on natural number risk limits, I suggest that you can close this issue, @ranweiler.  I'll let you do it for the pleasure of such.
