### ISSUE TITLE
Inform county users when they've missed deadlines

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#494]
Examples:
- Failed to upload a ballot manifest or CVR before audit is launched by DOS
- Failed to establish audit board before audit launch, then tries to launch audit

See: #186

**Comment by nealmcb** [comment]
> Failed to upload a ballot manifest or CVR before audit is launched by DOS

This is a deadline, and a notice to that effect is important.

> Failed to establish audit board before audit launch, then tries to launch audit
This can be resolved by just establishing the audit board, and isn't a deadline, I assume.

**Comment by kiniry** [comment]
I'm moving this issue to the next milestone, as it represents UI polishing.

**Comment by sfsinger19103** [comment]
> Failed to upload a ballot manifest or CVR before audit is launched by DOS

CDOS has asked for a message to the County including an email and a phone number (which CDOS will provide).

**Comment by sfsinger19103** [comment]
CDOS 9/11:

“You are unable to upload a file because the deadline has passed and the audit has begun. Please contact the CDOS voting systems team at rla@sos.state.co.us or 877-436-5677 for assistance.”
