### ISSUE TITLE
Implement end-of-round sign-off

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#514]
Blocked on #504, #506.

**Comment by sfsinger19103** [comment]
from CDOS 8/28 feedback:

After all of the CVRs have been audited the state dashboard indicates that there are 0 ballots to audit and the county page says that there are 0 ballots to audit, yet a CVR is presented to be audited. There should be a message that tells the county that this round of the audit has been completed.

**Comment by sfsinger19103** [comment]
From [CDOS mockup](https://docs.google.com/document/d/18ON3DJwn56puC0foO-gRJaXp45PckbM-BWnCVlDg4vg/edit#)

[Screen Nth]
After Audit Board submits reports on all ballots randomly selected for audit in this round for this county, RLA Tool should return and display the following certification page:

Audit Board:
Congratulations! You have completed reporting the votes on all ballots randomly selected for this round of the risk-limiting audit of the [County Name] County [Election Date] [Election Type] Election.
Please complete this audit round by entering your names in the fields below, making the following certification, and selecting Submit.  
By entering his or her name and selecting Submit below, each Audit Board member individually certifies that he or she:
Personally located and retrieved, or personally observed a county staff member locate and retrieve, each paper ballot randomly selected for [audit round no.] of the [County Name] County [Election Date] [Election Type] Election;
Personally examined each such randomly selected ballot;
Accurately entered the voter markings contained in each ballot contest on each such randomly selected ballot, to the best of his or her ability;
Where applicable, resolved ambiguous markings, over votes and write-in votes in accordance with the current version of the Secretary of State’s Voter Intent Guide;
In the case of physically duplicated ballots, if any, the Audit Board’s report reflects the voter markings on the paper ballot originally submitted by the voter.

Audit Board Member No. 1:		[Fillable fields for first and last name]
Audit Board Member No. 2:		[Fillable fields for first and last name]

**Comment by sfsinger19103** [comment]
Now blocked only on #506 (which is almost done anyway).

**Comment by ranweiler** [comment]
Note, per the CDOS mockup, we are *not* including the political party selector in this screen. If desired, we can add that as well.

**Comment by ranweiler** [comment]
Closed in #545.
