### ISSUE TITLE
Client behavior for County after file uploads before SoS starts audit

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#519]
From CDOS 8/28 feedback: 

After successfully uploading hte CVR and the ballot manifest files a message should appear to notify the county to "stand-by" until the state performs their part of the audit. The "Audit Board Sign-in" button should be grayed out until the state starts the audit.

**Comment by ranweiler** [comment]
Fixed as of #508. I will add a "stand-by" message, which will close this out.
