### ISSUE TITLE
Visual feedback for county waiting for file upload

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#520]
per CDOS feedback 8/28

After clicking the upload button for the CVR there is a long time without any indication of activity. The Upload button can be clicked multiple times. There should be a spinner and the Upload button and the Audit Board Sign-in button should be grayed out.

**Comment by ranweiler** [comment]
We currently indicate once (1) a file has been uploaded, and (2) a file has been imported. Disabling the upload button is a good idea, we can add some other "busy" indications as well.

**Comment by sfsinger19103** [comment]
Suggested message text to users:

When file has uploaded (but contents not necessarily processed): "File received, attempting to import content"
When file contents have been imported: "File content successfully imported"

**Comment by kiniry** [comment]
If you can get to the "busy" indicator for today's demo, that would be great.  The fact that the UI goes to the R/O state very quickly right now is good, but for CVR sets of size 10^5 or greater, the user doesn't know/understand that the upload is in progress since there is no UI feedback.

**Comment by sfsinger19103** [comment]
New text suggestions for messages during upload process:

*GREEN*, should appear and stay visible in this order:
Upload complete, checking hash of _filename_
Hash matches, starting data import
Data import complete

*RED*, only one should appear below any green:
Upload failed for _filename_ -- try again?
Hash mismatch -- check hash and try again?
Data import failed -- check file format?

**Comment by sfsinger19103** [comment]
Also, someone was talking about some data import progress indications (instead of a spinner) for large CVR files.
