### ISSUE TITLE
Delete the “Ballot Polling” option.

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#523]
Per CDOS 8/28 feedback.

**Comment by ranweiler** [comment]
I also updated the risk limit entry instructions to match current functionality. It now reads: "Each contest has a default risk limit set. To change the default risk limit, change the percentage shown."

We can modify it further, but that was just the simplest sensible reduction from the previous text.

**Comment by dmzimmerman** [comment]
Um... so we're setting a risk limit per contest? I don't believe the server supports that through any endpoint yet (though it does under the hood).

**Comment by ranweiler** [comment]
@dmzimmerman, no, it's just that the text I'm replacing said "Each contest type has a default risk limit set. To change the risk limit for a class, change the percentage shown. To change the risk limit for a particular contest use the link below to add an exception from the default."

Adding per-contest risk limits is another issue altogether. For now, I just want something sensible in the instructions. @sfsinger19103, if you have a suggested edit, let's open a new issue for it, please.
