### ISSUE TITLE
Risk limit as non-negative percentage

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#524]
Per CDOS 8/28 feedback

Entering the risk limit from the keyboard is impaired because the box does not accept a decimal point. It would be more useful if the input was in percentage with a trailing percent sign. The risk limit can be increased and decreased in steps of 0.01. The risk limit can be set to a negative number.

**Comment by ranweiler** [comment]
This was fixed in d4580255a9b638e8988e61023fcc19774e5ff8a5 and #385.
