### ISSUE TITLE
Show undervoted/blank voted contests consistently on review screen

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#526]
Per CDOS 8/28 feedback (screenshots in word file attached to 8/28 CDOS email)
[RLA Tool Feedback 08 28 2017.docx](https://github.com/FreeAndFair/ColoradoRLA/files/1259027/RLA.Tool.Feedback.08.28.2017.docx):

When no contests are marked with votes the review screen does not list any contests.
When the contest being audited is undervoted (blank) and other contests are voted the audited contest does not appear on the review screen. Presidential electors is not shown.

After changing the votes on a down-ballot contest and reviewing the audited contest did start to show as blank voted. Presidential Electors is now shown.

**Comment by sfsinger19103** [comment]
From the[ CDOS mockup](https://docs.google.com/document/d/18ON3DJwn56puC0foO-gRJaXp45PckbM-BWnCVlDg4vg/edit#):

[Screen 5]
Audit Board:  Please carefully review your report of voter markings on this ballot.
You have indicated that [randomly selected ballot no. ___] contains the following votes:
This is [randomly selected ballot no. ___] of [total no. of randomly selected ballots for this audit round] to be audited.
This is Ballot Style [_____]
Ballot Contest 1
Fremont County School District RE-1
Director, At-large
(Vote for Two)
	Al Abramson
	Camilla Carson

Ballot Contest 2
Fremont County School District RE-1
Director, First District
(Vote for One)
	Over vote – cannot discern voter intent

Ballot Contest 3
Fremont County School District RE-1
Ballot Issue 3A
(Vote for One)/(Vote Yes or No)
	Yes/For

Ballot Contest 4
Fremont County School District RE-1
Ballot Issue 3B
(Vote for One)/(Vote Yes or No)
	Blank vote

Audit Board:
If the above is correct, select Next to submit this report and go to the next randomly selected ballot.  

If the above is not correct, select Back to re-enter the votes contained on this ballot.

**Comment by sfsinger19103** [comment]
Also, if I enter no information on the ballot interpretation screen, clicking "Review" does nothing. But what if the ballot card is entirely blank?

**Comment by ranweiler** [comment]
The main issue here, along with the blank ballot card issue in the comment above, is closed in #602.
