### ISSUE TITLE
Back button does not return user to the session

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#527]
From 8/28 CDOS feedback:

This is related to [#174](https://github.com/FreeAndFair/ColoradoRLA/issues/174).

Under “Counties” from the menu when clicking on a county name the page is blank and using the back button does not return you to the session. I have to open a new browser window and log in again. 

When a contest is clicked the page is blank and using the back button does not return you to the session. I have to open a new browser window and log in again.

**Comment by sfsinger19103** [comment]
I tried to replicate this on `master` just now. From the SoS dash, when I clicked on a County name I was taken to the initial tool login screen.

**Comment by sfsinger19103** [comment]
Still seeing the behavior in from the previous comment, but when I log back in I'm on the page of the County whose name I clicked.

**Comment by kiniry** [comment]
I'm moving this to our next milestone.  For the moment make sure we carefully document this, @mkiniry and @sfsinger19103.

**Comment by ranweiler** [comment]
This was fixed in #674.
