### ISSUE TITLE
Prevent upload of zipped files without browser restart

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#529]
From 8/28 CDOS feedback:

Counties may be tempted to upload a zipped file of the CVR file, but the tool does not handle the upload file selection gracefully. The browser window needs to be closed in order to proceed.

**Comment by ranweiler** [comment]
If the uploaded file is zipped, then it will result in an unprocessable entity error. These should be gracefully handled now, definitely as of #426 and the switch to two-step uploads. I just tested with a zipped file, and got (1) an alert that the file was being uploaded, (2) an alert that the file could not be imported, and a suggestion to please check that it is valid. No browser restart is necessary.

**Comment by ranweiler** [comment]
If we can repro the need for a browser restart on the latest `master`, with very specific steps, we can reopen this.
