### ISSUE TITLE
Implement public audit dashboard

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#53]
Blocked on #52.

**Comment by sfsinger19103** [comment]
There is no need to implement the public audit dashboard on the front end, as CDOS requires F&F only to provide data for the public audit dashboard. From an email from SS explicitly accepted by Dwight Shellman on August 2:

> We now know that the implementation of the public-facing dashboard is being done by CDOS, not by F&F (though F&F will make sure that the RLA Tool provides the specified data, on the desired schedule, to the system controlling the public-facing SoS website).
