### ISSUE TITLE
Slow upload of CVR file

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#530]
Per CDOS feedback 8/28:

"A file of 1140 CVRs takes up to a minute to upload. Larger files will take much longer."

**Comment by sfsinger19103** [comment]
This has already been fixed as of 8/28. Can someone please document the tested upload times and close this issue? Thanks.

**Comment by kiniry** [comment]
Here are the current benchmarks, as tested on my laptop.  Times reported are in wall clock times, in seconds.  

```
# CVRs     time
100           18
1000        20
10000      33
50000      63
100000    261  (just over 4 minutes)
500000   6100 (1h 40m)
```
With the addition of a UI that indicates progress on the upload and parse, the current performance is fine for the `phase-3` release but for the largest counties.  (Four counties have greater than 300k voters.  If they have multi-card ballots, then that means four counties will have CVR files with over 600k entries.)

Recall that CDOS will be doing performance testing over the next 2-3 weeks.  If they find that these performance numbers for the largest counties are inadequate even with UI feedback, we'll have to have a conversation, as there is little we can do to get this faster.  The only thing we can do is make parsing a completely asynchronous event.

**Comment by kiniry** [comment]
Obviously there is an inflection point where the DB performance drops dramatically between 100k and 500k ballots.  We continue to do performance analysis on Postgres to determine the root of that degradation.

**Comment by dmzimmerman** [comment]
6100 is too high. Even on my old machine, the difference between 100000 and 500000 was much, much smaller than that. And it looks to me like the inflection point in those numbers is actually between 50000 and 100000.

**Comment by nealmcb** [comment]
We should try a 500000-CVR audit on their hardware for calibration.  I got a faster result (77 minutes, just the parsing step, based on the server log timestamps). If you have a database reset step during testing, that can add minutes to the overall operation (though of course that wouldn't be a problem in deployment, where database resets will be disabled).

**Comment by sfsinger19103** [comment]
Given the demo success yesterday, this issue can probably be closed!
