### ISSUE TITLE
Save election type and date, display in DOS and county dashboards

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#538]
Per @sfsinger19103:

> CDOS wants to have the info from the election type radio button on the first Audit Board screen. From the mock-up:
> 
> [Screen 1]
> [County Name] County [Election Date] [Election Type] Election
> Audit Board Reporting Utility for Risk-limiting Audit
> [State] [County] Ballot Contest
> Click here to proceed
> 
> https://docs.google.com/document/d/18ON3DJwn56puC0foO-gRJaXp45PckbM-BWnCVlDg4vg/edit

**Comment by kiniry** [comment]
More UI/UX polishing to move to the next milestone.

**Comment by ranweiler** [comment]
This is closed in #657, except for the "Screen 1" in the linked mockup, which we actually just don't have right now. Filing a separate issue for that.
