### ISSUE TITLE
Audit Board Screen 3

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#540]
Below is [CDOS mockup](https://docs.google.com/document/d/18ON3DJwn56puC0foO-gRJaXp45PckbM-BWnCVlDg4vg/edit#) of this page:

[Screen 3]
The Secretary of State has established the following risk limit(s) for the following ballot contest(s) to audit:  
[Contest Name] – [Risk Limit]
[Etc., if SOS selects more than one county contest for audit]
The Secretary of State has randomly selected [total number of ballots] for the [County name] County Audit Board to examine to satisfy the risk limit(s) for the audited contest(s).
The Audit Board must locate and retrieve, or observe a county staff member locate and retrieve, the following randomly selected ballots for the initial round of this risk-limiting audit:
[List randomly selected ballots, using the following convention, available from each county’s ballot manifest:]
Scanner no. __ / Batch no. __ / Ballot position no. __ / Storage bin [name] 
Scanner no. __ / Batch no. __ / Ballot position no. __ / Storage bin [name]
Scanner no. __ / Batch no. __ / Ballot position no. __ / Storage bin [name]
Scanner no. __ / Batch no. __ / Ballot position no. __ / Storage bin [name]
Scanner no. __ / Batch no. __ / Ballot position no. __ / Storage bin [name]
Scanner no. __ / Batch no. __ / Ballot position no. __ / Storage bin [name]
[Etc., until all ballots randomly selected for county are listed and displayed.  The randomly selected ballots should be listed and displayed for each county in ascending order of Scanner/Batch/Position nos.]

Audit Board:  Click Next to start reporting the votes you observe on each of the above ballots.

**Comment by ranweiler** [comment]
Closed in #559.
