### ISSUE TITLE
Risk Limit text

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#541]
Current text for risk-limit setting needs a rewrite:

> Risk Limits
> Each contest has a default risk limit set. To change the default risk limit, change the percentage shown.
> Comparison Audits (%)
> 
> 
> Once the election has started, this information will not be able to be changed.
> 

How is the immutability of the risk limit actually enforced in the tool?

**Comment by sfsinger19103** [comment]
As of right now, risk limit cannot be modified after it is set once (unless entire database is reset). 

Per Rule 25:
> No later than 32 days before election day, the Secretary of State will establish and publish on the Audit Center the risk limit(s) that will apply in RLAs for that election. 

For now, text rewrite should be: 

> Risk Limit
> Enter the risk limit for comparison audits as a percentage.
> 
> Once entered, this risk limit cannot be modified.

**Comment by sfsinger19103** [comment]
Maybe we should put a similar warning on the random seed entry:

> Once entered, this random seed cannot be modified.

**Comment by ranweiler** [comment]
Closed in #558.
