### ISSUE TITLE
Imported CVR Export "Undefined" green user feedback during upload

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#542]
I got a confusing message on upload of the 1140-CVR file we were sent today (8/29) by CDOS. The message was green, so I think it was a status message, but users might be alarmed by the word "undefined" in the message `Imported CVR export "undefined"`.

Let's avoid using "undefined" in a positive status message?

**Comment by ranweiler** [comment]
That's a bug; it should display the filename.

**Comment by ranweiler** [comment]
Closed in #558.
