### ISSUE TITLE
Add sort/filter on contest update box in DOS dashboard

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#546]
On SoS home page

**Comment by kiniry** [comment]
More UI polish, so moving milestones.

**Comment by sfsinger19103** [comment]
per [CDOS 9/1 feedback](Per https://docs.google.com/document/d/1GpusBIBClPRxmIVRhZrU9qdDAqwsgvvtfdhGDjuDh9Q/edit):

> The contests are listed in a somewhat random order that is not the ballot order defined in the CVR. There are not sort and filter functions.
 
We plan to sort/filter by County. If it's easy, let's do it by contest name as well.

**Comment by sfsinger19103** [comment]
CDOS wants this on the Select Contests page too.

**Comment by sfsinger19103** [comment]
Per 9/5 conversation, CDOS wants the Contest Update Table on the SoS main page to show only contests that the SoS has "selected for audit" per Rule 25.

**Comment by ranweiler** [comment]
Note that I am treating this issue as _only_ about the sort/filter. I made a separate issue for the above comment by @sfsinger19103.

**Comment by ranweiler** [comment]
Created #714 for the select contests form.
