### ISSUE TITLE
Script to build client and server.

### ISSUE THREAD

**Issue by mkiniry** [FreeAndFair/ColoradoRLA#547]
Can someone please write script that automagically builds the client and server and DB and runs the server for interactive testing purposes?

**Comment by nealmcb** [comment]
It all depends on which build methods you like and how you want to manage things and watch for errors etc.

For now you can do this in one window:
```
cd client
npm install
npm start
```
and this in another
```
cd test/smoketest
./smoketest.bash
```
And then visit http://localhost:3000/county and hit "Reset Database" when you're done admiring the results of the finished smoketest :)

Setting up and monitoring multiple windows automatically depends much more on your local tools (tmux? screen? byobu?) etc.

**Comment by kiniry** [comment]
What we want is the full database delete, server build, server start, credential load, client build, client run sequence in one go.  This is for interactive, not automatic, testing.  I'll get to this soon if no one else does.
