### ISSUE TITLE
Info doesn't flow through to DOS County detail page

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#554]
After some audit activity in Adams County (audit board signs in, reviews some ballots) I see 22 ballots audited and 22 discrepancies.

Switching to the SoS dashboard in the other browser, I looked at the page localhost:3000/sos/county/1 in the SoS dashboard. The page has a check mark in the "Started" row, but Ballots Submitted and Discrepancies are blank. And the Audit Board is listed as John Doe and Jane Smith, which are not the names Adams County entered.

**Comment by kiniry** [comment]
This bug is still present.  In particular, the audit started column does not represent the county's audit state.

**Comment by dmzimmerman** [comment]
The audit board information is, I'm fairly sure, not being sent to the DoS dashboard. That's easy to fix. I am curious as to where it's getting that info from in the first place in that case, though.

**Comment by dmzimmerman** [comment]
(then again, I'm not familiar with that page... @ranweiler, are you loading the county dashboard refresh for that page, or the part of the DoS dashboard refresh that has county info?)

**Comment by ranweiler** [comment]
Temporarily disabled these pages. Will revisit.

**Comment by kiniry** [comment]
This is UI polish, so I'm moving it to the next milestone.

**Comment by ranweiler** [comment]
This is fixed now, except for the audit board, which we don't yet get in the DOS app. Opening a new issue for that.
