### ISSUE TITLE
re-uploading a different CVR results in erroneous behavior of both dashboard types

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#561]
If a county uploads a new and different CVR (i.e., one with different contests), then:
- the County Dashboard refreshes and shows both old CVR and new CVR contests
- the State Dashboard goes into a bad UI state that doesn't permit user interaction, including logout

For both Dashboards, logging out and logging back in shows the correct data.

**Comment by ranweiler** [comment]
Probably due to a deep merge where we should just be setting a new value. Investigating.

**Comment by ranweiler** [comment]
I know why this is happening, and the fix is relatively subtle. I probably won't get to this pre-demo.

**Comment by kiniry** [comment]
But will you get to it pre-`phase-3` release?
