### ISSUE TITLE
moving to the Contest Overview page (/sos/contest) causes DOS Dashboard to become unresponsive

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#562]
Something is borked with the Contests page, above and beyond the attempt to click on Contest names to pass through to Contest pages, which doesn't work and the hyperlink should be removed, IMO; see #279.  Right now when I hit this page my DOS Dashboard UI goes unresponsive.

_(edited by @ranweiler to fix a swapped word)_

**Comment by ranweiler** [comment]
Temporarily disabled those pages. Will revisit soon.

**Comment by kiniry** [comment]
Moving to the next milestone as this is UI/UX polish.
