### ISSUE TITLE
One contest goes south in Round One, all others are perfect

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#589]
Suppose that in Round One the Adams County County Commissioner race is under audit, and the Audit Board there finds tons of overvotes.

Suppose the Audit Boards in other counties find no overvotes in any race.  Perfect agreement between aCVRs and CVRs.

What happens in Round Two? What does Boulder County see on their home page?

**Comment by nealmcb** [comment]
The size of a round for a county-specific contest in one county doesn't affect the size of a round in other counties.

In addition, note that multi-county contests must not be selected to drive the number of ballots to audit in the current implementation.  In the future, when that is supported, there can be a number of ways that this situation can be handled for contests that span multiple counties, ranging from requiring all counties to escalate, to requiring just the county with lots of discrepancies to escalate, to somewhere in-between, depending on a variety of factors and policy decisions.

**Comment by nealmcb** [comment]
See also #590.
