### ISSUE TITLE
Difficult contest sent to full hand count -- how are round length calculations adjusted?

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#590]
Note: I've started this issue in Phase 3, though we may triage it to later. It's a real issue, though. 

Suppose Adams County Commissioner race is under audit and Audit Board finds tons of overvotes in Round One. 

Suppose that at the same time the Boulder County Commissioner race is under audit, and the Audit Board in Boulder finds a few overvotes in that race in Round One

Suppose all other contests in all counties have perfect agreement in Round One.

Suppose the Secretary of State wants to call a full hand count for Adams County, but not for Boulder County. 

Will the RLA Tool assign a sensible number of ballot cards to Boulder County in Round Two?

**Comment by sfsinger19103** [comment]
I worry that if the RLA Tool does not allow the Secretary to change the status of Adams County Commissioner race to "hand count", Boulder County may suffer unnecessarily.

**Comment by kiniry** [comment]
The RLA algorithm is applied to each contest in each county separately, so the fact that one count moves to a hand count has no impact at all on any other county.
