### ISSUE TITLE
Drop down menu for write-in candidates

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#591]
From CDOS Audit Board Utility Mockup:

If audit board reports a vote for write-in candidate, a drop down menu should appear with additional reporting choices:
[First and last name of first qualified write-in candidate for this contest]
[First and last name of second qualified write-in candidate for this contest]
[Etc., for as many write-in candidates as qualified for this ballot contest]
Unqualified write-in candidate

**Comment by kiniry** [comment]
We still need clarification from CDOS on this UI and behavior, given the rarity of write-ins being competitive in contests.  Given they haven't brought up write-ins in any call or email, keeping this in `someday` is appropriate.

**Comment by sfsinger19103** [comment]
Pending confirmation from CDOS after 9/6 phone conversations (Dwight and Stephanie): this feature not necessary for Nov 2017 version.  Instead, we'll use the comment box (See #661 )

**Comment by kiniry** [comment]
I'm including a request for confirmation in Weekly Report #11 on this issue.

**Comment by ranweiler** [comment]
Note that we've closed #661. Leaving this open in the `someday` milestone because we'd eventually like to in some way visually distinguish _qualified_ write-ins.

**Comment by dmzimmerman** [comment]
Indeed. It may be worth actually modifying the data structures now to track this information, given that I have to come up with a robust way to deal with the "Write-in" candidate anyway.
