### ISSUE TITLE
# of ballots per County list < # of ballots remaining in round per State dash

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#593]
County sees 105 ballots to audit in Round Two

<img width="1146" alt="countyaudit105" src="https://user-images.githubusercontent.com/14353822/29952792-8891f1b0-8e80-11e7-81b2-2fa3fc22dff6.png">

**Comment by sfsinger19103** [comment]
![bug_round_two](https://user-images.githubusercontent.com/14353822/29952801-97fa4da0-8e80-11e7-8bcf-1fdcf3b0e197.png)

**Comment by kiniry** [comment]
Did I review a PR where this off-by-one error was taken care of, @ranweiler?

**Comment by ranweiler** [comment]
This is now fixed, definitely as of #672.
