### ISSUE TITLE
Download list of acvrs, discrepancies and other data needed to verify the calculations

### ISSUE THREAD

**Issue by nealmcb** [FreeAndFair/ColoradoRLA#601]
To augment and substantiate the audit reports specified in #473 and #474, and the specifications of the various algorithms for random selection and risk level calculation (which are embodied in this open-source software, along with any configuration parameters that are relevant and should also be published), the full set of data necessary to verify the calculations of the risk levels achieved needs to be made available to the losers, the voters, and other interested parties.

This set of data downloads should be provided in standard formats like csv or json, and should include:

* The CVRs and manifests from each county
* The random seed selection, which, given given the selection algorithm, allows for recreation of the raw random sequence, and with the CVR and Manifest, allows for recreation of the sequence for any given county.
* The full set of ACVRs (Audit CVRs), including:

    * The selection sequence number, Ballot ID and Audit Board interpretations of each sampled ballot.
    * An assessment for each contest on the acvr of whether there was a match with the corresponding CVR, a 1- or 2-vote overstatement of the margin, or a 1- or 2-vote understatement of the margin.
    * The time of entry for each CVR, manifest, or ACVRs upload.

For the latter, it would probably make sense to use the same format that is used for CVRs. with the addition of the selection sequence number and timestamp at the beginning of the row, and the addition of a numeric discrepancy column for each contest, before the set of columns for the choices.

Update: include the "comments" field which was entered along with the ACVR upload, and whether there was "no consensus". Also include "ballot not found" reports.

Update: The detailed results and calculations to be verified should also be provided in a format which is easy to work with. See e.g. an interim example csv file:  [discrepancies.csv.txt](https://github.com/FreeAndFair/ColoradoRLA/files/1464161/discrepancies.csv.txt)

**Comment by nealmcb** [comment]
The SQL query in `test/corla-acvrs.psql` can return all the ACVRs, note were there are discrepancies, and show the choices for each contest in both the original CVR and the ACVR.
It does not yet break down the exact kind of discrepancy, but provides enough information to re-create it.  So an endpoint for use by each county which retrieved their county-specific information based on a query like this would go a long way towards resolving this issue.

**Comment by nealmcb** [comment]
To verify the calculations, it is also necessary to check that the outcome of tabulating the CVRs matches the preliminary outcome that is being audited, for each contest.

The outcomes, vote counts and margins calculated by the audit tool can be retrieved via another SQL query, available in `test/smoketest/tabulate.sql`, which produces output like that at  `test/smoketest/tabulate.out`.  Anyone checking the results of the audit should compute their own tabulation from the downloaded CVRs, which can then be compared with these results.

**Comment by nealmcb** [comment]
Here is a [sample csv file](https://github.com/FreeAndFair/ColoradoRLA/blob/0376c13332fe7377f47fe6148d7392ccf8c4617f/test/smoketest/acvr_report.csv) resulting from the query at [test/corla-acvrs.psql](https://github.com/FreeAndFair/ColoradoRLA/blob/master/test/corla-acvrs.psql)

**Comment by sfsinger19103** [comment]
Note #751 has just one component of this issue, allowing BM and CVR file download by State user.

**Comment by nealmcb** [comment]
Closed with rla_export command in #810
