### ISSUE TITLE
404s in server log

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#605]
I'm still seeing regular 404s in the server log:
`00:22:16,646 ERROR corla:452 - error 404 data not found on /cvr-to-audit-list: parameter validation failed by countyadmin2 from localhost:8888`

**Comment by dmzimmerman** [comment]
These are almost certainly bad requests. The server is not doing anything wrong here - parameter validation succeeds if either of these is true:

- both `start` and `ballot_count` are parseable as integers and >= 0
- `round` is parseable as an integer and >= 0

**Comment by ranweiler** [comment]
This is not a server bug at all, we just need to not make requests if we don't have certain data on the client.
