### ISSUE TITLE
What should happen on 2FA failure?

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#610]
Right now, it just gives you an error message and sits at the same page.

**Comment by ranweiler** [comment]
Does the requested behavior actually make sense? Doesn't that mean the user should retry?

**Comment by kiniry** [comment]
We don't know what they really want, because they haven't started testing 2FA.

**Comment by ranweiler** [comment]
Based on the above and other conversation, we'll move this to the next phase until it is clear what should change, and how.

**Comment by ranweiler** [comment]
@kiniry, have we received any user feedback on this? If there's something that we should change, I'm having trouble reproducing any issues locally, so I need repro instructions, and/or to coordinate with you to ensure we get good behavior when use the proprietary 2FA.

**Comment by ranweiler** [comment]
I think the current behavior is appropriate now, as of #813. If it needs to change, please open an issue with what the expected behavior should be.
