### ISSUE TITLE
ballots under audit table tweak

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#618]
Should table of ballots under audit listed on the audit board page also include a sequence number column?

**Comment by nealmcb** [comment]
The counties want the capability to sort their ballots either by location or by random selection sequence number, both in the client and in a spreadsheet via a downloaded CSV file. See spec at #125.

**Comment by sfsinger19103** [comment]
CDOS gave us a spec, which doesn't include a sequence number column, nor any download for the County other than a printable list of ballots [#628](https://github.com/FreeAndFair/ColoradoRLA/issues/628). For the UI/UX polishing milestone, I think we should leave this as is. Move to "Sumeday" milestone?

**Comment by ranweiler** [comment]
This would be easy to add, but we need to decide if it is desired. We should ask CDOS, and/or change the milestone.

**Comment by sfsinger19103** [comment]
CDOS 9/11:
Yes [please add the column for ballot status]. On this page could you also show the ballot type of each ballot? That would be useful information for the audit board to know if they have found the correct ballot as they are pulling it from the bin which might be located in another room.

![image](https://user-images.githubusercontent.com/14353822/30303472-33f97f74-971d-11e7-984a-52c32b079adc.png)
