### ISSUE TITLE
Default order of contests in Contest Update table and on Select Contests page

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#619]
Let's ask CDOS how they use this table and use that to choose a default order.

From [CDOS 9/1 feedback](https://docs.google.com/document/d/1GpusBIBClPRxmIVRhZrU9qdDAqwsgvvtfdhGDjuDh9Q/edit).

**Comment by sfsinger19103** [comment]
CDOS wants this in both places where contests are listed (home page and select contest page)

**Comment by dmzimmerman** [comment]
From the server side, going forward ( these will be delivered in order first by county ID and then by import order, unless we hear that they want some other order.
