### ISSUE TITLE
User can Launch Audit before Random Seed is accepted

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#626]
![image](https://user-images.githubusercontent.com/14353822/29987317-76231f1c-8f1c-11e7-81a1-226466457dc8.png)

**Comment by dmzimmerman** [comment]
It should no longer be possible to get the server/database into a bad state in this way given recent ASM changes.

**Comment by ranweiler** [comment]
This is fixed on the server-side. Will disable the "Launch" button unless we succeed in setting the seed.
