### ISSUE TITLE
Report two categories of discrepancies (for audited & non-audited contests)

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#636]
The audit reported that there were discrepancies, but the total number of discrepancies apparently includes discrepancies in the audited contest and discrepancies in the non-audited contests. The discrepancies should be separated into two categories: one for all audited contest and one for all non-audited contests on both the state and county pages.

Does this issue require a change on the server side?

**Comment by dmzimmerman** [comment]
We need clarification on this. Do they want:

- a count of the number of ballots that have discrepancies in audited contests, and a count of the number of ballots that have discrepancies in non-audited contests
- a count of the _total number of discrepancies_ in audited contests (across all of them), and a count of the _total number of discrepancies_ in non-audited contests (across all of them)
- something else?

**Comment by dmzimmerman** [comment]
Also, does the same proposed change apply to disagreements (lack of consensus)? (the same questions apply there too)

**Comment by sfsinger19103** [comment]
Subsumed in #655
