### ISSUE TITLE
"Click to download intermediate audit report" message even for final audit report

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#652]
On County home page.

**Comment by sfsinger19103** [comment]
Message appears also at beginning of audit board activity, when there is (presumably) no report to download. In this case clicking the button does nothing. Can this section be suppressed, or can the button at least be grayed out?

**Comment by ranweiler** [comment]
The "final" part of this was closed in b12d924 . Addressing the initial state issue.

**Comment by ranweiler** [comment]
I just checked, and we currently only enable the download button when the endpoint genuinely returns a file with valid information. Even if no audit board has signed in or done anything, there is still a valid intermediate audit report that can be downloaded, so there's no reason to try to disable the button. Closing.
