### ISSUE TITLE
End of Round messages for County

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#654]
From CDOS 9/5 conversation.

On end-of-round page, status messages to County should be clear.

JoeK, do you remember what CDOS said they wanted here? I'm having trouble recreating it. --S.

**Comment by ranweiler** [comment]
Blocked pending inquiry to CDOS on details.

**Comment by sfsinger19103** [comment]
SS email to CDOS 9/11:

My notes from our conversation of 9/5 indicate that CDOS wanted clearer messages to the County on the End-of-Round page. We're not confident that we understand what you have in mind. Can you share some sample messages? Or just explain the general idea?

**Comment by sfsinger19103** [comment]
CDOS 9/11 says messages in v1.0.0a1 are OK.
