### ISSUE TITLE
Revised CVR file format; new error messages needed for upload

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#656]
To comply with Colorado law protecting voter anonymity, CDOS will ask Counties to remove the "counting group" column from the CVR file before hashing and uploading the file. 

To do:

1. alter server-side as necessary to process file without the column
2. if the column of the CVR file has not been deleted, refuse to import contents to db
3. if the column of the CVR file has not been deleted, give County user an error message:
"Import failed. Please remove Counting Group column, rehash and re-upload."

**Comment by dmzimmerman** [comment]
(1) and (2) are easy. (3) is harder, and requires introducing a concept of _why_ a parse failed rather than just failure or success. Unless it is absolutely essential to also do (3), it's much easier to just do (1) and (2).

**Comment by sfsinger19103** [comment]
About (3):  we do provide a generic "import failed" message when upload succeeds but import fails. In v1.0.0alpha1, message was "Please verify that the uploaded file is a valid CVR export". 

We could alter that message to read "Please verify that the uploaded file is a valid CVR export with the County Group column deleted."

That would go a good distance toward meeting the CDOS concern, and it's just a text change in the client, right?

**Comment by nealmcb** [comment]
The actual spelling of the column header is `CountingGroup`, not "counting group" or "County group".
I think `PrecinctPortion` should also be deleted for our purposes since it also may present an anonymity issue.

In some samples of CVRs we've seen, the `BallotType` field has included precinct information also, which would be a problem, but of course we want the `BallotType` (ballot style) field for other purposes, so somewhere along the line they should ensure that `BallotType` doesn't include precinct information.

**Comment by sfsinger19103** [comment]
We'll do it to CDOS's spec, which is currently to assume only CountingGroup column should be deleted.

**Comment by dmzimmerman** [comment]
Yes, @sfsinger19103, that message change would go a long way toward meeting their concern without requiring more error handling logic in the server. I did think of a reasonable way to do the error handling logic, that won't take much effort, so I could do it anyway (for `CountingGroup` removed only); I'll see.

**Comment by dmzimmerman** [comment]
Hey, important question here: is it the intent that they should delete the _contents_ of the "CountingGroup" column, or the entire column? Because if they delete the entire column it actually changes the file format and makes us unable to test with regular CVR export files, but if they only delete the _contents_, it's straightforward to check that the column is empty. Either way is fine, but we need to decide on one.

**Comment by sfsinger19103** [comment]
The intent is to delete the entire column. In other words, if the original CVR file has the CountingGroup column  in between the column for FieldA and the column for FieldB, the file for upload will have the column for FieldA immediately preceding the column for FieldB.

**Comment by nealmcb** [comment]
FWIW, my preference would be for the parsing to key off column headers, rather than implicitly thinking it knows e.g. that the 4th column is `ImprintedId`. Then they could remove one or more columns without breaking the parser.

**Comment by dmzimmerman** [comment]
I can certainly modify it to do that; that makes sense under the circumstances, though their files are weird in that "column headers" are in the same row as "contest choice explanations".

**Comment by nealmcb** [comment]
Oh, right, indeed! That "csv" file is about as non-standard as they come, with the header row in question being the 4th actual row, half normal headers and half sub-sub-headers of the contest/candidate info with optional party affiliations.
How could I have forgotten.... You're doing beyond-the-call-of-duty work parsing that stuff....

**Comment by dmzimmerman** [comment]
And... it's done. See the branch.

**Comment by sfsinger19103** [comment]
@nealmcb per conversation 9/8 with Dwight Shellman, for 2017 the condition of use for Counties will require the CountingGroup column to be deleted but will *not* ask for deletion of PrecinctPortion.

**Comment by sfsinger19103** [comment]
This is a bad look, since the cvr was in unredacted format. Yes, it was uploaded, so the message is not incorrect. But the disappearance of the warning messages before the disappearance of the green could be misleading.

![unredacted](https://user-images.githubusercontent.com/14353822/30411718-9a31b724-98c7-11e7-9fea-486ab88e45d1.png)
