### ISSUE TITLE
County audit start screen 1

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#659]
Implement Screen 1, as depicted in the mockup here: https://docs.google.com/document/d/18ON3DJwn56puC0foO-gRJaXp45PckbM-BWnCVlDg4vg/edit (F&F access only)

This screen is specified by the following text from the above document:
```
[Screen 1]
[County Name] County [Election Date] [Election Type] Election
Audit Board Reporting Utility for Risk-limiting Audit
[State] [County] Ballot Contest
Click here to proceed
[ Next ]
```

It's actually not clear exactly what is being specified here, particularly the `[State] [County] Ballot Contest
` part of the mockup. Investigate.

**Comment by ranweiler** [comment]
@sfsinger19103, can you please find out what is expected for the section of the page I highlighted?

**Comment by sfsinger19103** [comment]
CDOS 9/11:
The audit board utility page should indicate the audited contest, i.e., whether it is the audited state ballot contest or audited county ballot contest selected for audit by the Secretary of State, in accordance with Rule 25.2.2(i). So it should read “Adams County audited state ballot contest” or “Adams County audited county ballot contest”.

**Comment by ranweiler** [comment]
@sfsinger19103, per our discussion elsewhere, this is still confusingly-spec'd because it is talking about a single contest. Presumably we are supposed to list all contests under audit here, along with if they are state/county. Is _that_ confirmed yet?

**Comment by sfsinger19103** [comment]
9/12 F&F has asked for clarification: what if there is more than one contest under audit?

**Comment by sfsinger19103** [comment]
Per SS recollection of conversation with CDOS 9/12, new spec for Screen 1 is:

[County Name] County [Election Date] [Election Type] Election
Audit Board Reporting Utility for Risk-limiting Audit
Click here to proceed
