### ISSUE TITLE
Reduce clickable area associated with radio buttons

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#689]
E.g., from CDOS RLA Tool Feedback #2 (9/11):

Inadvertently clicking anywhere to the right of the election type choices can select a different election type than intended. The target area should be limited to the radio button and the election name text.

This is an issue on the Ballot Verification page too, for voter choice radio buttons.

**Comment by sfsinger19103** [comment]
And on audit board sign-in page (political party radio buttons)

**Comment by sfsinger19103** [comment]
On audit board sign in page you can still toggle a radio button by clicking way to the right of the text. `4e9f3047d52b0d86552cd46ad862f80510f5e042`
--

**Comment by ranweiler** [comment]
@sfsinger19103 and I have identified this as a cross-browser issue. Fix found and incoming.

**Comment by sfsinger19103** [comment]
CDOS reports (in RLA Tool Feedback #1_tool version2) seeing this issue in the second (9/15) deliverable. 

Email question 9/21 from SS to one CDOS technical staff:

> Quick question on the first open issue from the RLA Tool Feedback #1  Version 2:
> 
> 	Inadvertently clicking anywhere to the right of the election names can select a different election type than intended. The target area should be limited to the radio button and the election name text. 
> 
> We fixed and tested this in Chrome, Safari and Firefox. What browser were you using when you saw this behavior?
