### ISSUE TITLE
Date formats (date of election and date of public meeting)

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#691]
Currently when election date and public meeting date are set they appear on an SoS page in this format: 2017-11-23. This might not be what CDOS wants.

**Comment by sfsinger19103** [comment]
Also on this page: sos/audit/seed

v1.0.0.alpha-1 used the more common 11/23/2017 format. I conclude that CDOS wants this format. 

Change all dates to this format.

**Comment by ranweiler** [comment]
I went with `M/D/YYYY`, which gives, for example, `1/2/2017`, instead of `01/02/2017`. This can be easily adjusted if needed.

**Comment by sfsinger19103** [comment]
M/D/YYYY is a great choice for this audience.
