### ISSUE TITLE
CDOS reports slow upload & other problems in their instance

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#693]
Summary of problem [here](https://drive.google.com/open?id=0B5_BzTbq3XxPRW1BMkdxbUxXRmM)

Files used in test are [here](https://drive.google.com/open?id=0B5_BzTbq3XxPSUhITXVUb2MybXc)

**Comment by ranweiler** [comment]
This is with release `v1.0.0-alpha-1`, right?

**Comment by sfsinger19103** [comment]
Yes. v1.0.0-alpha-1.

**Comment by dmzimmerman** [comment]
Note that they determined this was a result of them running out of disk space.
