### ISSUE TITLE
Enable flagging contests for hand-count

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#696]

**Comment by dmzimmerman** [comment]
This is a more complicated issue than one might think (as briefly noted in Slack), and we probably need to discuss how we're going to handle it.

**Comment by sfsinger19103** [comment]
culled from CDOS communications, fyi:

-  "the tool must have the capability to allow the SOS to display the status for counties that are hand counting"

- information for public dash was to include "Status (audit required, audit in progress, audit complete, hand count required,, hand count complete) by Contest "

**Comment by sfsinger19103** [comment]
Blocked on #726

**Comment by ranweiler** [comment]
Removing some labels to narrow this issue down to the server-side. #742 captures the client side.
