### ISSUE TITLE
Round 0 in Progress?!

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#700]
Not sure how I got here:

(Edit by @ranweiler) Expand details below for image (warning: flashing screen):
<details>

![round 0](https://user-images.githubusercontent.com/14353822/30406671-21f867c2-98a8-11e7-879e-c34bdfe9b2ce.png)

</details>

**Comment by dmzimmerman** [comment]
Interesting. It looks to me as though we have a situation here where no counties actually need to audit (one says "audit complete", the other missed their deadline) given the risk limits assigned, and somehow we're not catching that fact and going to the audit complete state. I will check on the server side and see whether that's a thing I need to fix.
