### ISSUE TITLE
"# Ballots to Audit" blank 

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#704]
http://localhost:3000/county

SoS just launched Round 2.
![blank_bs2audit](https://user-images.githubusercontent.com/14353822/30439306-4509f53e-9928-11e7-9a13-84a139c11b66.png)

**Comment by sfsinger19103** [comment]
And after first ballot in round is audited, problem persists. # ballots audited still blank.

**Comment by ranweiler** [comment]
@sfsinger19103, I'm interpreting the missing number as the ballots to audit _remaining in the round_, not the overall estimate. Please confirm/deny.

**Comment by sfsinger19103** [comment]
Is all the info in the last four lines round-specific?

**Comment by sfsinger19103** [comment]
From the RLA Tool Feedback #2, it seems they want to see the number of ballot cards in the round, not the number remaining to audit. Can we change text to "# Ballot Cards in Round"?

**Comment by sfsinger19103** [comment]
Upshot: yes, @ranweiler , confirmed:

> the missing number as the ballots to audit remaining in the round


(and I'll move the langague changes to a new issue)
