### ISSUE TITLE
Audit Board gets red message on successful completion of audit round

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#705]
Saw this after Audit Board signed off on Round 2. Error message is not strictly incorrect, but red signals to user that a mistake has been made, which is not the case. 
![notready](https://user-images.githubusercontent.com/14353822/30439759-7a9f364a-9929-11e7-9b96-0be4166f0150.png)

**Comment by ranweiler** [comment]
Didn't quite get to this, will address in next phase.
