### ISSUE TITLE
Show total per-contest discrepancy counts on DOS dashboard

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#710]
Blocked on #743.

**Comment by ranweiler** [comment]
Didn't quite get to this, moving to next milestone.

**Comment by dmzimmerman** [comment]
OK. This may give me a chance to figure out how to do the calculations for out-of-order ballots in a round in a principled way that yields less surprising results.

**Comment by ranweiler** [comment]
Still blocked. We now have a `discrepancy_count` key in the DOS dashboard refresh response, but it never updates.

**Comment by dmzimmerman** [comment]
Are you sure about that? I thought we established previously that it does update, but only with respect to the random sequence prefix rather than the sequence ballots are presented in.

**Comment by ranweiler** [comment]
Updated #743 to capture the need for discrepancy computations that won't confuse the user via a dashboard-observable mismatch.
