### ISSUE TITLE
Add sort/filter on DOS Select Contests form 

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#714]

**Comment by sfsinger19103** [comment]
from RLA Tool Feedback #1_tool version3.docx:

16.  The contests on the state page are listed in the order that the counties uploaded files to the tool. A method to sort by county name would be helpful. See Test Case #9.

So need to add sort (not just filter).

**Comment by ranweiler** [comment]
This issue is about the select contests form. Let's move any discussion about this to #814.
