### ISSUE TITLE
Firefox reporting errors

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#723]
Firefox reports errors during use, could impact user confidence.

<img width="630" alt="firefoxerrorwarning" src="https://user-images.githubusercontent.com/14353822/30499440-655aa788-9a0f-11e7-80ba-f1dce902e6db.png">

**Comment by ranweiler** [comment]
These are not errors, but just logging statements, but your point would stand. However, in our production bundles, we disable them, so this is already addressed.

If you do encounter actual _errors_, however, please open new issues for each error (with screenshot or text), so I can address them individually. Thanks!

**Comment by sfsinger19103** [comment]
> we actually had the debug statements on intentionally, so we could ask them to look in the browser console for more info when they started testing
> but i disable that in prod builds in my WIP branch
> either way, it isn't a "bug" any more than the existence of the "reset database" button is a bug.
> it is a feature to support testing, which should be turned off before real deployment
-- from JoeR
