### ISSUE TITLE
"Audit Started" checked for all counties when none have taken action

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#725]
No County has even uploaded anything, yet SoS page (http://localhost:3000/sos/county) shows check marks in "Audit Started" column for all Counties.

<img width="752" alt="countyupdatenull" src="https://user-images.githubusercontent.com/14353822/30508582-05306de4-9a4f-11e7-8d2a-2a8e055b4d08.png">

**Comment by ranweiler** [comment]
Instead of a checkmark in an "Audit Started" column, we now render a human-readable audit status in a "Status" column, just like in the county updates section of the dashboard home page.
