### ISSUE TITLE
Moving to hand counts

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#726]
Suppose we  are in the middle of Round Two of the audit. Suppose the contest for Mayor of Hipville in Beauty County is showing an alarming number of discrepancies -- so many discrepancies, in fact, that the Secretary of State decides to call for a hand count. In the RLA Tool the Secretary of State clicks the box for "hand count" for this contest.

First suppose that the contest for Mayor of Hipville was _not_ originally selected for audit by the Secretary of State. What exactly should happen? Specifically,

1. Should the RLA Tool change its behavior in any way other than listing the status "hand count required" in each table status of individual contests?

Next suppose that the contest for Mayor of Hipville _was_ selected for audit by the Secretary of State during the audit definition. What exactly should happen? Specifically,

1. Should the RLA Tool continue to present Round Two ballot card review pages to the Audit Board of Beauty County? 
2. If not, what behavior is desired from the "Audit" page of RLA Tool in Beauty County during Round Two?
3. What behavior is desired from the "Audit" page of RLA Tool in Beauty County at the end of Round Two?
4. At the end of Round Two, how should the RLA Tool calculate the number of ballot cards for Round Three? Presumably, since the Hipville Mayor contest is in hand count, the discrepancies from that contest should not be included in the calculation.
5. During the remainder of Round Two and for any subsequent Rounds, should the numbers of discrepancies (resp., disagreements) reported in the RLA Tool by County include the discrepancies (resp., disagreements) stemming from the Hipville Mayor contest?
6. During the remainder of Round Two and for any subsequent Rounds, should the numbers of discrepancies (resp., disagreements) reported in the RLA Tool by contest include the discrepancies (resp., disagreements) stemming from the Hipville Mayor contest?

What other questions do we need to ask CDOS in order to implement the hand count feature? @dmzimmerman , your input will be particularly appreciated.

**Comment by sfsinger19103** [comment]
Conversation with @nealmcb today leads me to believe that we may be able to implement something intelligent without asking CDOS for direction. Or maybe there's a much more limited question we'd like to ask them. I'm trusting @dmzimmerman and @kiniry will figure out what needs to be asked and ask CDOS as soon as possible.

**Comment by sfsinger19103** [comment]
per JoeK in Slack: "They have agreed to our recommendations in the last weekly report [Weekly Report #11] wrt handling switching to a hand count", namely:

Question: Moving to a hand count.  If an audit is going poorly for one reason or another, then the SoS may decide to move to a hand count for a contest or contests in a county.  If such a determination is made, and the RLA Tool provides a means by which to signal such, which of the following then happens?
**Answer: The entire audit in the contest’s county is halted.**

Note that from context "the entire audit" means the entire RLA-Tool enabled audit. (From a legal point of view, the resulting full hand count is part of the "audit").

**Comment by ranweiler** [comment]
Done when #696, #742 are.

**Comment by ranweiler** [comment]
I believe this is now done, since #696 and #742 are. @sfsinger19103, if you agree with that, please close this issue. Thank you!
