### ISSUE TITLE
# of counties in round and # of counties completed are incorrect on SoS dash

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#728]
In this case one county (Adams) had no contest selected for audit.
One county (Alamosa) is in the middle of round one
One county (Arapahoe) has finished round one (and won't need to review ballots in round 2).

Reasonable people could disagree: 
- 1 of 2 Counties have finished this round
or
- 2 of 3 Counties have finished this round.

But certainly 
- 0 of 1 Counties have finished this round
isn't correct.
    

<img width="1174" alt="240_county_updates_mid_round" src="https://user-images.githubusercontent.com/14353822/30515221-c3a0d26c-9ad8-11e7-945f-8e7cb5759d64.png">

**Comment by ranweiler** [comment]
In the given example, we now display the "1 of 2" interpretation. The county with no contests never participated in the round, so they don't count towards the total. The other two counties both started the round, so they do count towards the total.
