### ISSUE TITLE
Ensure DOS final audit report can be downloaded

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#729]
Per the [RLA Tool Export Requirements](https://docs.google.com/document/d/19PPv2qtvb2pDM0C4k3A0mWPgQ1lJnf71VP_SFoWSv10/edit), 

State Exports
List of CVRs to audit for each round for each county – sorted by imprinted ID
Ballot Verification summary report for each county – county, round #, results of audit for each round
Summary report of the entire statewide audit. The report should include:
   * County
   * Audited contest(s)
   * Choice and vote totals for winner
   * Choice and vote totals for loser
   * Margin between winner and loser in votes
   * Number of ballots cast
   * Diluted margin in percentage
   * Number of ballots that were audited, by round, in each county

**Comment by dmzimmerman** [comment]
Is there a specific part of this that has been flagged as not already existing? (Other than, perhaps, the cleanup of those margin columns so they only show margins for the winner(s)?

**Comment by sfsinger19103** [comment]
Might be just a client-side issue -- I found no button on the State site allowing a user to download.

**Comment by ranweiler** [comment]
All of this info appears in the Excel file in the intermediate audit report. We just need to make sure it is available when the audit is complete.
