### ISSUE TITLE
License information in UI

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#737]
We need to add prominent notice of license information in the UI, probably in both the splash screen and in an "about" page.

> If you modify the Program, your modified version must prominently offer all users interacting with it remotely through a computer network (if your version supports such interaction)  an opportunity to receive the Corresponding Source of your version by providing access to the Corresponding Source from a network server at no charge, through some standard or customary means of facilitating copying of software. _ https://www.gnu.org/licenses/agpl.html#section13

**Comment by ranweiler** [comment]
@kiniry, I assume by "splash" screen you mean the first step (password part) of the login page. Is that correct? I also assume we should link to it in the menu or menu bar. What do you think makes the most sense?

**Comment by ranweiler** [comment]
Also, does the copyright _owner_ actually need to display such a notice, or just anyone who uses the program under the AGPL?

**Comment by kiniry** [comment]
My thoughts are:
 - the Copyright and License information might be summarized in a small typeface in a footer

**Comment by kiniry** [comment]
IANAL, but I do not think it is mandatory for the Copyright owner to display either the copyright or the license notice, but I think it _wise_ for them to do so.  It is up to their lawyers to figure this out, not ours.

**Comment by ranweiler** [comment]
@kiniry understood. In some ways, it is actually easiest to add an "About" page with that info, and link to it wherever we like. There will be less competition for screen real estate, and we can have lots of room to even display the entire license, if we like.

My request is just that someone exactly specify (1) what text be on this page, (2) where the links should be, and in what format. My proposal for (2) is an "About" menu item, which links to a page at `/about`.

**Comment by ranweiler** [comment]
@kiniry, I see you updated your comment. I'm going to implement a footer with link, per your recommendation.
