### ISSUE TITLE
update all copyright declarations

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#739]
The RLA Tool is a work-for-hire product for the Colorado Department of State.  As such, they hold the copyright to this work until we hear otherwise.  We should automatically rewrite all copyright documentation comments to reflect this and clarify such in the project's README and LICENSE docs.

**Comment by nealmcb** [comment]
Baded on http://www.sos.state.co.us/pubs/info_center/terms.html  the copyright holder would be "Colorado Secretary of State" but we should confirm that.

**Comment by sfsinger19103** [comment]
Question has been posed to the F&F legal department.

**Comment by dmzimmerman** [comment]
This being the case, what should I do with the source file copyright notices?

**Comment by nealmcb** [comment]
Closed in #816
