### ISSUE TITLE
Add "Hand Count" button to DOS contests under audit

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#742]
If that button is pressed, then it should log that fact and the RLA calculation should no longer act on that contest. The time of that declaration of hand count and the administrator who called it should be securely logged.

~~Blocked on #696.~~

**Comment by dmzimmerman** [comment]
The time of the declaration and the administrator who called it will be logged, as with anything else, but _retrieving_ that information would not be trivial. Does that matter? 

Does this have to happen for any of our upcoming deliverables, or is it really "someday"?

**Comment by ranweiler** [comment]
@dmzimmerman, I am currently double-checking on the timeframe for this and related issues.
