### ISSUE TITLE
Include per-contest discrepancy counts in DOS dashboard response

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#743]
Compute the per-contest discrepancies as each ACVR comes in within a round, not dependent on reaching a certain prefix in the random audit sequence.

**Comment by ranweiler** [comment]
Current status: we have a `discrepancy_count` key in the DOS dashboard refresh response, but it never updates.

**Comment by dmzimmerman** [comment]
They won't match anyway, for reasons I gave in Slack, namely:

> the “audit the ballot as soon as it’s submitted, not when we get to it in the sequence” change, while leading to more reasonable looking changes in estimates, will still leave possible confusion with respect to counts of contest discrepancies; the overall counts will still count _ballots_ with discrepancies, while the contest counts will count _elements of the random sequence_ with discrepancies. This is the case for two reasons: first, replicating the audit calculations requires that they know the actual numbers of discrepancies _in the random sequence for each contest_ that are being used to do the calculations… and second, we simply don’t track the number of _ballots_ with discrepancies in the individual contest audit calculations, which is where those numbers come from, because… well, it’s not useful information.

**Comment by dmzimmerman** [comment]
Also:

>I don’t think the numbers of discrepancies in individual contests and the number of discrepancies reported county-wide will ever “match” (unless we change the county-wide ones to be “total number of discrepancies across all contests”) because of duplicates, and because some contests will have discrepancies while others will not. They will, however, be _current_ at the same time (assuming my changes actually worked correctly).
