### ISSUE TITLE
Date and time format in reports

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#747]
Date and Time format: CDOS doesn't like "military time" or "insignificant digits". Change:

- "Generated" datetime to "9/18/2017 3:51pm" 
- election date format to "8/21/2017" 

(per RLA Tool Feedback #1_tool version2, in reference to County Audit Report).

**Comment by dmzimmerman** [comment]
OK. The right time for them to have mentioned this, by the way, was when they first saw the audit reports (the deliverable that they ended up accepting as phase 1). There's nothing _wrong_ with the date or time format - they are ISO standards. They are asking for something non-standard, which is fine, and we will provide it, but it is not reasonable to consider it a defect in the system when they don't specify what they want, in any way, and they get a standard ISO date format as a result of that lack of specification.

**Comment by dmzimmerman** [comment]
This was closed by #752. I guess I forgot to note it there.
