### ISSUE TITLE
Allow State user to download County-uploaded BM and CVR files

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#751]
(Note: this is one component of #601 ).

Requested by CDOS in RLA Tool Feedback #1_tool version2.

**Comment by dmzimmerman** [comment]
It is not clear to me that we have any obligation to do this for this week, since it's a new feature they had never asked for before this round of feedback. I can probably get the server side done quickly, but the client/UI side may be harder.

**Comment by sfsinger19103** [comment]
Agreed, but I hope we can do it for the fourth & final release milestone.

**Comment by ranweiler** [comment]
I opened #758 for the client part of this.
