### ISSUE TITLE
logged out from /sos/ after clicking on "County" in breadcrumbs

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#757]
Working in Safari, logged in as stateadmin, 

In nav menu, clicked on "County". 
In County list, clicked on "Arapahoe".
In breadcrumbs, clicked on "County"
Got sent to the login screen!

Logged back in as a stateadmin (including 2fa)
Landed on the /sos/county page.

**Comment by ranweiler** [comment]
@sfsinger19103, would you please try to repro this for me on the latest `master`?

**Comment by ranweiler** [comment]
Note: can't repro on Debian with Chrome 60 or Firefox 52.

**Comment by sfsinger19103** [comment]
Can't repro on Safari.

**Comment by ranweiler** [comment]
Great, thanks @sfsinger19103! Closing, but please reopen if you find you can repro at some point.
