### ISSUE TITLE
Add buttons to download CVR export and ballot manifest

### ISSUE THREAD

**Issue by ranweiler** [FreeAndFair/ColoradoRLA#758]
This is the UI piece of #751. Should be available on both DOS and county dashboards.

**Comment by ranweiler** [comment]
For the county dashboard, there is an obvious place to add the file download buttons. However, it isn't clear where the bests spot is for the DOS dashboard. Should it be on the dashboard home page? If so, we need a button for each county, which would suggest adding columns to the "County Updates" section.

I think a more reasonable place would be in the County Detail pages for each county (e.g. `/sos/county/1`), where we have lots of room, and perhaps the County Overview (`/sos/county`) page. Thoughts, @sfsinger19103, @nealmcb?

**Comment by sfsinger19103** [comment]
Both places suggested in the previous comment make sense to me.
