### ISSUE TITLE
Exports for public dashboard

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#768]
per Email Jerome Lovato to SS 7/24, the following should be included in the export for the public dashboard:
a.    Seed for randomization
b.    Random ballot order
c.     Number of ballots to be audited overall in each audited contest in each county
d.    List of Audit Rounds (number of ballots, status by County, download links).   Links shouldl be to all the finalized ballot-level interpretations and comparison details, in sufficient detail to independently verify the calculated risk levels. [as allowable by CORA]

e.    Status (audit required, audit in progress, audit complete, hand count required,, hand count complete) by audited contest (i.e., contest "selected for audit" by SoS

f.      Link to Final Audit Report 
g.    Audit Board names and political parties by County
h.    County Ballot Manifests and Hashes (status & download links)

**Comment by sfsinger19103** [comment]
Here are some thoughts from CDOS about how often updates should happen.

per Email from Trevor Timmons to SS  8/8:

F&F question: How often, and how quickly, should updates be exported from the RLA Tool for updates to the public dashboard?
CDOS: Response: Well, we’ve had a couple different thoughts on this.
One thought is that it should function similarly to our election night reporting interface, which leaves the control to a human being to initiate the export. That way, the people in our office who are overseeing the activity can communicate the schedule they’ll be using for publication to counties, and everyone will know exactly when the export occurs. That could be done by adding “export” functionality to the administrative interface.
The other thought is to make it configurable, perhaps by using cron or some other means of allowing this to be a scheduled activity. This could theoretically still be enabled through the admin interface. Automation of the export capability opens a lot more doors to increasing or decreasing the frequency of publication without requiring a lot of brain cells after the decisions are made.
Until we have a better idea of the throughput of the system under actual use, we will probably plan on once or twice daily exports. If the tool is up to the task, we can consider more frequent updates.

**Comment by sfsinger19103** [comment]
I'm worried that the public may be confused by this: 

> c. Number of ballots to be audited overall in each audited contest in each county

since we can only provide the length of the random sequence, not the number of physical ballot cards.

**Comment by sfsinger19103** [comment]
Now that CountingGroup column is supposed to have been redacted from the CVRs by the counties, maybe they can add CVRs to the list.

**Comment by sfsinger19103** [comment]
Should the "Audit Board" be the *current* audit board? Or a history of all Audit Boards for the County in the current election?

**Comment by dmzimmerman** [comment]
It is not the case that we can only provide the length of the random sequence; we know how many ballot cards are in each round, too, so we can provide that information. In fact, we already do as part of the DoS dashboard refresh and county dashboard refresh.

**Comment by dmzimmerman** [comment]
I think our current status on this is the following:

>a. Seed for randomization

in DoS dashboard refresh

> b. Random ballot order

easily obtainable in JSON format from the `/cvrs-to-audit` endpoint

> c. Number of ballots to be audited overall in each audited contest in each county

Not available, and not going to be available in this version of the tool, unless this number reflects _ballots that count toward the audit calculations for that contest_ (that number is the same for all contests in the county, because every audited ballot in the county counts for every contest in the county).

> d. List of Audit Rounds (number of ballots, status by County, download links). Links shouldl be to all the finalized ballot-level interpretations and comparison details, in sufficient detail to independently verify the calculated risk levels. [as allowable by CORA]

This one might need some work, but should be easy.

> e. Status (audit required, audit in progress, audit complete, hand count required,, hand count complete) by audited contest (i.e., contest "selected for audit" by SoS

Available on the DoS dashboard refresh now

> f. Link to Final Audit Report

They can download it and put it anywhere they want

> g. Audit Board names and political parties by County

Not exported right now (except for the _current_ audit board, which is in the dashboard refreshes), but could easily be added to final reports or elsewhere.

> h. County Ballot Manifests and Hashes (status & download links)

Accessible from DoS dashboard refresh and file download endpoint, will be accessible through UI soon

**Comment by nealmcb** [comment]
Re:
> c. Number of ballots to be audited overall in each audited contest in each county

In advance, an RLA never knows how many ballots _will_ be audited. We calculate an _intiial sample size_, and based on the numbers of discrepancies and their types, we update the sample size, which may lead in general to additional rounds, or, if allowed in some alternative deployment, to ending a round early if it turns out that the leading candidate actually got _more_ votes than initially reported.  It is also possible that the audit goes to a full hand count.

But as noted above, we can report how many votes have already been audited, and estimates of the remaining number, based on a variety of forecasting approaches.

**Comment by nealmcb** [comment]
Issue #601 "_Download list of ACVRs, discrepancies and other data needed to verify the calculations_ " documents the progress towards a report that presents the evidence necessary for (d) for the public to independently verify the calculated risk levels. It includes downloading the "acvrs" - the Audit Board interpretations, ala a CVR, of each audited ballot card, along with the other data, which must include the original CVR upload, so they can independently:

 * check it against the hash value which was announced prior to the random selection,
 * tabulate it
 * confirm that the random seed and the random selection algorithm produce the same selections
 * confirm that the comparisons between the Audit Board ACVR interpretations and the committed CVRs are correct.
 * see any comments made by the Audit Board during the auditing.

**Comment by dmzimmerman** [comment]
> In advance, an RLA never knows how many ballots will be audited. We calculate an intiial sample size, and based on the numbers of discrepancies and their types, we update the sample size, which may lead in general to additional rounds, or, if allowed in some alternative deployment, to ending a round early if it turns out that the leading candidate actually got more votes than initially reported. It is also possible that the audit goes to a full hand count.

While this is true, in the case of CORLA, with its round structure, we _do_ know how many ballots will be audited in each round; which is, really, as far as we can forecast since we never know whether they're going to ask for another round.

**Comment by sfsinger19103** [comment]
Thanks @dmzimmerman and @nealmcb these comments will help in crafting the exact questions to CDOS.

@dmz, re this comment:

> b. Random ballot order
> easily obtainable in JSON format from the /cvrs-to-audit endpoint, but I probably need to tweak the endpoint so that DoS can access any county they want with a query parameter rather than only counties being able to access it (and probably we also would want the output sorted by random order rather than by ballot identifier); alternatively a new endpoint could be written for this that does not sort by ballot identifier and is used only for export purposes

random sequence of ballots is infinite, so I was imagining CDOS meant some kind of list, with dupes, that the public could use to check against their own calculations of the random sequence (based on random seed and the PRG). In that case, wouldn't we need to supply a list with dupes? When do we actually calculate the list from the PRG -- do we do it only at the beginning of each round?

@nealmcb, what would CORLA 2 or other similar groups want to see on the Audit Center (aka public dash)?

**Comment by sfsinger19103** [comment]
Drafting questions for CDOS here: https://docs.google.com/document/d/1VSrgMXmfDTA_T7NjScHopQeHzTS69i74xROoyQCQRAA/edit

**Comment by dmzimmerman** [comment]
> random sequence of ballots is infinite

The beauty of that endpoint is you can ask it for whatever range of the sequence you want - in this case you’d ask it for all elements, including duplicates and audited elements, from 0 to the audited prefix length achieved by the final round in each county. But it’d be nice if there were a shorter way of saying that, which didn’t require you to _know_ the audited prefix length achieved by the final round in each county a priori (i.e., “give me the entire sequence through all the rounds that have occurred or are in progress”), which is what I was alluding to when I mentioned making another endpoint (or, I suppose, adding a new parameter to the existing one).

**Comment by sfsinger19103** [comment]
In reference to the list in @nealmcb 's most recent comment: can anyone give a specific example scenario in which independent verification of the audit calculation depends on the comments typed by the audit board into the RLA Tool? 

In other words, in what scenario does omitting the comments make the difference between independent verifiability of the audit calculations and lack of independent verifiability of the audit calculations?

**Comment by sfsinger19103** [comment]
Per discussion 9/27 with @ranweiler @dmzimmerman @nealmcb @sfsinger19103, CDOS can get info out of the RLA Tool and into the CDOS-hosted public Audit Center by using database queries, which @sfsinger19103 will write.

**Comment by nealmcb** [comment]
A tool which is possibly of value to help make a human-readable (HTML) presentation of the output, via @ranweiler, is https://datatables.net/

**Comment by nealmcb** [comment]
Closed with `rla_export` command in #810
