### ISSUE TITLE
Graceful server behavior in case of tied contest

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#773]
The RLA Tool is not required to support the audit of a contest for which the CVRs indicate an exact tie. 

However, should that case arise, the RLA Tool should behave gracefully and give useful information to the user. 

Operationally, the RLA Tool will have sufficient information when a CVR file with a tied contest is uploaded. (Note that, although Rule 25 asks the Secretary of State to choose contests for audit on the Friday after Election Day, which is before the Counties will have uploaded CVR files, the SoS can identify a contest in the RLA Tool only after the CVR files for that contest has been uploaded by the County.

How should this be implemented? Here's an idea to start the discussion:
 
> as part of the processing of any uploaded CVR file, change the status of any tied contest automatically to "hand count required"?

**Comment by sfsinger19103** [comment]
See issue #774 for the client side.

**Comment by ranweiler** [comment]
Per hangout on 9/27: @dmzimmerman will, upon manifest + CVR export upload, determine if any given contest is a tie. Then, in the structure in which the client already receives contest info, we will flag a contest as unable to be audited. I suggest somehow being explicit about the reason (in this case, reported tie), but this is not necessary. The important thing is that this flagging data is available from the server API at the time that the DOS admin selects contests for audit.
