### ISSUE TITLE
Graceful client behavior in case of a tied contest

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#774]
See issue #773  for the server side. 

How should the client help the SoS avoid choosing a tied contest for audit in the RLA Tool? Should the sos/audit/select-contests page have a contest status column (which might be automatically set by the server to "hand count" in case of a tie)?  Or should the checkbox for a tied contest be disabled, with some kind of message by the checkbox? Or should checking the box for a tied contest throw an error message (e.g., "this contest is tied and cannot be used to determine a risk level")?

**Comment by ranweiler** [comment]
Our plan for the client: in the DOS contest selection screen, display that some contests have been selected for hand count, but do not allow them to be selected for audit. This lets users know that the contests were processed, are _intentionally_ not available as audit choices, and why that is the case.
