### ISSUE TITLE
language change in Audit Report

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#786]
7.     Change “OPPORTUNISTIC_BENEFITS” TO “Unaudited contests” on the audit report Excel spreadsheet. 

from RLA Tool Feedback #1_tool version3.docx

**Comment by dmzimmerman** [comment]
It will be "Unaudited Contest" (singular), because it makes no sense to have a plural "Audit Reason", but other than that, this is straightforward.
