### ISSUE TITLE
Measure of upload progress

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#789]
11.  Given the long time that some counties will have to wait with only the circle spinning to indicate that something is happening a status indicator that gives the progress status as either the percentage of completion or the number of records imported is very desirable.

from RLA Tool Feedback #1_tool version3.docx

**Comment by ranweiler** [comment]
We won't be able to add this feature for the final release, as it would require significant server and client changes.

**Comment by dmzimmerman** [comment]
Indeed. I'm not quite sure what the "right" way to do it would be, to be honest.

**Comment by ranweiler** [comment]
@dmzimmerman I have some ideas, with or without approximation, so this is a valid issue for `someday`.
