### ISSUE TITLE
Better, more timely info for State user about county audit and round statuses

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#790]
13.  When a county completes an audit round the state page does not automatically update the number of counties that have completed the round. To get an update the state has to log off and log back on. See Test Case #7.

from RLA Tool Feedback #1_tool version3.docx

**Comment by ranweiler** [comment]
@sfsinger19103, I _can't_ reproduce this issue in my local testing environment, but I _can_ on our test server. I don't know why that is, and will investigate with @dmz or @kiniry.

**Comment by ranweiler** [comment]
Note that in my bug repros, a logout is not necessary: a browser refresh is sufficient.
