### ISSUE TITLE
Intermediate Audit Report margins reported for vote-for-two contest

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#793]
The intermediate audit report indicates that the contest is a vote for 1 contest and that the margin is between the winning candidate with the highest number of votes and the winning candidate with the second highest number of votes, not between the winning candidate with the second highest number of votes and the losing candidate with the highest number of votes. The margin in this case should be 46, not 1.
 From Test Case #8 in RLA Tool Feedback #1_tool version3.docx

**Comment by dmzimmerman** [comment]
Should have been fixed by #778

**Comment by sfsinger19103** [comment]
Yes, fixed.
