### ISSUE TITLE
Two votes in a vote-for-two contest reported as "overvote" on Ballot Review Screen

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#794]
From Test Case #8 in RLA Tool Feedback #1_tool version3.docx

**Comment by dmzimmerman** [comment]
This has nothing to do with the server.

**Comment by dmzimmerman** [comment]
Fixed, presumably, in #778 by my fixing of the parsing issue. @ranweiler, please confirm.

**Comment by ranweiler** [comment]
Confirmed fixed in #778.
