### ISSUE TITLE
Pulling list of ballots to audit in each County

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#795]
18.  The state is required to post the ballots to be audited in each county on a website before the audit is started. How does the state obtain this information?

**Comment by nealmcb** [comment]
These lists by county can currently be generated via the smoketest framework. E.g. this command is for `county_id` 3, and includes duplicates:
`./main.py -e '/cvr-to-audit-download?round=1&county=3&include_audited'`
If `&include_duplicates` is added to the query, a list with one row per selection is available, which makes it easier to check the random selection algorithm itself.

These outputs will be included in #768, so I'm closing this issue as a dup.
