### ISSUE TITLE
State aCVR info export

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#798]
20.  How does the state see the results entered by the county into the tool by ballot and by contest? 

from RLA Tool Feedback #1_tool version3.docx

**Comment by nealmcb** [comment]
This information is discussed in #601, and there is a query identified there to get that data for the Audit Center.

**Comment by ranweiler** [comment]
Per chat, I don't believe there's any client component to this, and any export will be handled out-of-band. Removing the `client` label.

**Comment by dmzimmerman** [comment]
There is no additional server implementation for this either; it will be handled by database query.

**Comment by nealmcb** [comment]
Since this information is already included in the test/corla-acvrs.psql query, and will be included in #768, I'm closing this issue as a dup.
