### ISSUE TITLE
State Audit-Board-Comments export

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#803]
21.  How does the state see any comments entered by the county into the tool by ballot and by contest?

(from RLA Tool Feedback #1_tool version3.docx).

This information is discussed in #601 , and there is a query identified there to get that data for the Audit Center: `test/corla-acvrs.psql`

**Comment by nealmcb** [comment]
Since comments are already included in the `test/corla-acvrs.psql` query, and will be included in #768, I'm closing this issue as a dup.
