### ISSUE TITLE
manifest_hash.sql shows hash of all successfully uploaded manifests, not just most recent

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#848]
E.g. if Adams successfully uploads two bm files, there will be two lines in the result of the query

SELECT co.name as county_name, uf.hash AS ballot_manifest_hash
FROM county AS co
LEFT JOIN uploaded_file AS uf 
ON co.id = uf.county_id
WHERE (hash_status = 'VERIFIED' AND status = 'IMPORTED_AS_BALLOT_MANIFEST') OR uf.county_id is NULL 
ORDER BY county_name
;

**Comment by dmzimmerman** [comment]
This is actually a server bug; the only file that _should_ be marked in the database as imported is the most recent one, since all the records from the others get wiped.
