### ISSUE TITLE
acvrs.sql column meanings

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#849]
SELECT cai.index as selection, dashboard_id AS county, imprinted_id, record_type, timestamp, counted, disagreement,
   discrepancy, cci_a.comment, cci_a.consensus, cci_s.contest_id, cai.cvr_id, cci_s.choices as machine_choices, acvr_id, cci_a.choices as audit_board_choices
 FROM cvr_audit_info AS cai
 LEFT JOIN cast_vote_record AS cvr
   ON cai.acvr_id = cvr.id
 LEFT JOIN cvr_contest_info AS cci_s
   ON cai.cvr_id = cci_s.cvr_id
 LEFT JOIN cvr_contest_info AS cci_a
   ON cai.acvr_id = cci_a.cvr_id
     AND cci_a.contest_id = cci_s.contest_id
 ORDER BY cai.index, cci_s.contest_id 
;

sample output row:
         6 |      1 | 1-5-32       | AUDITOR_ENTERED | 2017-10-25 13:01:12.121 | t       | ["OPPORTUNISTIC_BENEFITS"] | ["STATE_WIDE_CONTEST","OPPORTUNISTIC_BENEFITS","TIED_CONTEST"] |         | YES       |      10245 |  10594 | ["Mike Smith / Daniel White"]               |   12050 | ["Hillary Clinton / Tim Kaine"]

Questions below

**Comment by sfsinger19103** [comment]
What are the options, other than `AUDITOR_ENTERED`, for the `record_type` field? What information does this field add to the output table, since most columns will be blank if the cvr in question has not been audited?

**Comment by sfsinger19103** [comment]
What is the purpose of including `cvr_audit_info.index as selection`? Isn't that index an internal database variable with no extrinsic meaning for the public?

**Comment by dmzimmerman** [comment]
For the `record_type` field, `UPLOADED`, `AUDITOR_ENTERED`, `PHANTOM_RECORD`, and `PHANTOM_BALLOT` are the possibilities.

**Comment by sfsinger19103** [comment]
This table is no longer part of the export.
