### ISSUE TITLE
Same ballot shown over and over in 1.0.4

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#863]
doing a little audit to test db queries, and I’m getting bad behavior: the system keeps showing me the same ballot to review, over and over. I'm in Safari. 
Clicking log out icon has no effect. 
Refreshing the window (command-R on my mac) yields a blank window. 
Closing the window and opening a new one yields the log-in screen; then navigating to the audit shows the ballot as "audited" on the Ballot Cards to Audit screen, and I'm offered the correct next ballot to audit.

Using this version:
commit d7f8a69494a7dd4d89d0dd88c9d5ec32b38ce0f1 (HEAD -> master, origin/master, origin/HEAD)
Merge: 5dcb52dc 9b6e911e
Author: Daniel M. Zimmerman <dmz@acm.org>
Date:   Thu Oct 26 23:25:19 2017 -0700

**Comment by ranweiler** [comment]
This was the intersection of a server issue (fixed in #859) and a client issue (fixed in #864).
