### ISSUE TITLE
coincidental ACVR ballot style match initially renders input from previous ACVR

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#867]
Per feedback from CDOS today, copied into Slack.  The refresh of the new ACVR to a proper, blank ACVR takes over 10 seconds.  They should never see the old markings.

I'll ask them if they want some status messages to automatically disappear and others to stay until they are closed manually, and precisely how long they want the messages to stay up.

**Comment by ranweiler** [comment]
Adding that this bug behaves "over 10 seconds" when the server is under high load. If not under load (e.g. when developing locally), it looks like a tiny blip. By using `tc`, we can recreate what users are seeing in high-load scenarios. We'll fix this by (1) transitioning at a more appropriate time (slightly later), (2) indicating that we are waiting for responses in high-latency situations.
