### ISSUE TITLE
many duplicate ballots listed in County report

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#868]
From CDOS (10/26 email from Jessi Romero to SS): the sample report given to us was pulled after 5 ballots were audited of the 53 ballots to be audited.  The remaining question is, why were there so many duplicates in the round page of the sample provided? Some ballots were listed 47 times, another was 40, etc. Only after removing duplicates, did we come to the 53 total ballots.  

[county_report_1.xlsx](https://github.com/FreeAndFair/ColoradoRLA/files/1432312/county_report_1.xlsx)

**Comment by nealmcb** [comment]
If a ballot id occurred identically in 47 counties, it would show up 47 times, because the query was not limiting in all cases to just the county being reported on. This is now fixed.

**Comment by sfsinger19103** [comment]
Is it correct to say that if CDOS runs rla_export on their current version (v.1.0.5, right?) then they will get a County Report without duplicates?

**Comment by nealmcb** [comment]
Yes. This issue was resolved.
