### ISSUE TITLE
change to behavior of notification messages

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#870]
CDOS would like error and warning notification messages (those that are now red and yellow) to be modal, and those that are informational (green) to have a 10 second timeout.

**Comment by ranweiler** [comment]
We _cannot_ make that type of notification element modal without significant dev time/rewriting. We _can_ change the timeout very easily.

**Comment by ranweiler** [comment]
Per chat, by "modal" @kiniry only meant "requires manual dismissal", not necessarily blocking other user interaction. We _can_ do that easily.
