### ISSUE TITLE
evaluate maintenance and monitoring tools for DB choice

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#88]
In particular:

- check_postgres https://bucardo.org/wiki/Check_postgres
- postgres-xc  https://postgres-xc.sourceforge.io/
- postgrest https://github.com/begriffs/postgrest

**Comment by nealmcb** [comment]
It looks like Postgres-XC moved from sourceforge to github in 2013 and changed its name to Postgres-X2: https://github.com/postgres-x2/postgres-x2

**Comment by kiniry** [comment]
Now that we have begun performance testing, such as @nealmcb's recent upload of 200+MB CVR files, I'll look into these tools soon.  Moving to `phase-3`.

**Comment by kiniry** [comment]
Moving to the next milestone in support of CDOS.

**Comment by kiniry** [comment]
I have reviewed these tools and am including the relevant ones in the deployment documentation.
