### ISSUE TITLE
rla_export script needs to be able to pull data while state & county folks are using the systems

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#881]
From Nov 3 email from Joe Bianchi: "We cannot confirm the rla_export tool works as we cannot switch from EntrustAuthentication to DatabaseAuntentication while the Counties and Elections folks are currently using the system"

**Comment by nealmcb** [comment]
We've confirmed that CDOS can and has pulled database query exports. The reported error messages did not interfere with the main job of rla_export, which is exporting results of database queries. Support for 2FA for streamlining the download of reports from the java server (which is what the errors were about) will be considered separately in #883.
