### ISSUE TITLE
Audit board enters comment and submits ballot; comment not recorded in database

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#889]
Query below was made a few minutes after submission of a ballot card review with text entered in the comment box. The db did have a record of the audit board review of the ballot in question, but no comment was recorded.

```
corla=# select distinct comment from cvr_contest_info ;
     comment      
------------------
 
 ballot not found
(2 rows)

corla=# 

```

**Comment by dmzimmerman** [comment]
I have tested this by modifying the Python smoketest client to submit comments with its ballots, and those comments ended up in the database. So I don't think this is a server-side issue.

**Comment by dmzimmerman** [comment]
This is definitely a client issue; the client is using the JSON key `comments` for the comments, but the key on the server side is actually `comment`.

**Comment by dmzimmerman** [comment]
This is a worse client issue than I thought. The client is, in fact, simply never sending comments - incorrect key or no. Verified by Wireshark monitoring of client/server connection.
